-- =============================================================================
-- Flyway V14 (PostgreSQL) — 웹진(Webzine) 이슈(호)·기사·본문 섹션·갤러리·태그
-- =============================================================================
-- PK: bigint GENERATED BY DEFAULT AS IDENTITY
-- 계층: webzine_issues → webzine_articles → sections / gallery_images / tags
-- 이슈/기사 삭제 시 ON DELETE CASCADE 로 하위 행 정리
-- =============================================================================

-- 웹진 호(이슈): URL용 slug, 정수 권호(volume)는 각각 유일
create table if not exists webzine_issues (
    id bigint generated by default as identity primary key,
    slug varchar(80) not null, -- 공개 URL 경로용 고유 식별자
    volume integer not null, -- 인쇄물 스타일 권호(1, 2, 3, …)
    issue_date date not null, -- 발행일(표시·정렬)
    cover_image_url varchar(500) not null, -- 표지 이미지 URL
    teaser varchar(1000) not null, -- 목록/공유용 짧은 소개
    created_at timestamp not null default current_timestamp, -- 생성 시각
    updated_at timestamp not null default current_timestamp, -- 마지막 수정 시각
    constraint uk_webzine_issue_slug unique (slug),
    constraint uk_webzine_issue_volume unique (volume)
);

-- 기사: 이슈당 slug 유일(동일 이슈 내 기사 URL)
create table if not exists webzine_articles (
    id bigint generated by default as identity primary key,
    issue_id bigint not null references webzine_issues(id) on delete cascade, -- 소속 이슈
    slug varchar(150) not null, -- 기사별 URL 슬러그(이슈 내 유일)
    title varchar(200) not null, -- 제목
    kicker varchar(200) not null, -- 상단 작은 헤드라인/카테고리 톤
    summary text not null, -- 요약/리드
    hero_image_url varchar(500) not null, -- 상단 풀폭 이미지
    card_image_url varchar(500) not null, -- 목록 카드 썸네일
    category varchar(30) not null, -- 분류 키
    format_label varchar(60) not null, -- 인터뷰/리포트 등 포맷 라벨
    author_name varchar(120) not null, -- 표시용 저자명
    author_email varchar(255) not null, -- 연락/메타용 이메일
    credit_line varchar(255) not null, -- 사진·출처 등
    highlight_quote varchar(500), -- 인용 강조(옵션)
    created_at timestamp not null default current_timestamp, -- 생성 시각
    updated_at timestamp not null default current_timestamp, -- 마지막 수정 시각
    constraint uk_webzine_article_issue_slug unique (issue_id, slug)
);

-- 이슈별 기사 목록 조회용
create index if not exists idx_webzine_articles_issue_id on webzine_articles(issue_id);

-- 기사 본문을 순서 있는 블록(섹션)으로 분리
create table if not exists webzine_article_sections (
    id bigint generated by default as identity primary key,
    article_id bigint not null references webzine_articles(id) on delete cascade, -- 소속 기사
    display_order integer not null, -- 렌더 순서
    heading varchar(200), -- 소제목(없으면 null)
    body text not null, -- 본문(HTML/마크다운 등 앱 규약에 따름)
    note varchar(1000), -- 각주·편집자 주(옵션)
    created_at timestamp not null default current_timestamp, -- 생성 시각
    updated_at timestamp not null default current_timestamp, -- 마지막 수정 시각
    constraint uk_webzine_article_section_order unique (article_id, display_order)
);

-- 기사 하단 갤러리 이미지(순서 보존)
create table if not exists webzine_article_gallery_images (
    id bigint generated by default as identity primary key,
    article_id bigint not null references webzine_articles(id) on delete cascade, -- 소속 기사
    display_order integer not null, -- 갤러리 내 순서
    image_url varchar(500) not null, -- 이미지 URL
    created_at timestamp not null default current_timestamp, -- 생성 시각
    updated_at timestamp not null default current_timestamp, -- 마지막 수정 시각
    constraint uk_webzine_article_gallery_order unique (article_id, display_order)
);

-- 기사 태그(동일 기사 내 tag_name 유일, 표시 순서는 display_order)
create table if not exists webzine_article_tags (
    id bigint generated by default as identity primary key,
    article_id bigint not null references webzine_articles(id) on delete cascade, -- 소속 기사
    display_order integer not null, -- 태그 나열 순서
    tag_name varchar(80) not null, -- 태그 문자열
    created_at timestamp not null default current_timestamp, -- 생성 시각
    updated_at timestamp not null default current_timestamp, -- 마지막 수정 시각
    constraint uk_webzine_article_tag_name unique (article_id, tag_name)
);
