-- Newsletter admin domain tables for PostgreSQL
-- 뉴스레터 목록과 상세 본문을 안정적으로 관리하기 위한 마스터/태그/문단 테이블을 생성한다.

create table if not exists newsletters (
    id bigint generated by default as identity primary key,
    slug varchar(160) not null,
    title varchar(200) not null,
    category_label varchar(80) not null,
    published_at date not null,
    image_url varchar(500) not null,
    summary text not null,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,
    constraint uk_newsletter_slug unique (slug)
);

create table if not exists newsletter_tags (
    id bigint generated by default as identity primary key,
    newsletter_id bigint not null references newsletters(id) on delete cascade,
    display_order integer not null,
    tag_name varchar(80) not null,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,
    constraint uk_newsletter_tag_name unique (newsletter_id, tag_name)
);

create table if not exists newsletter_paragraphs (
    id bigint generated by default as identity primary key,
    newsletter_id bigint not null references newsletters(id) on delete cascade,
    display_order integer not null,
    body text not null,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,
    constraint uk_newsletter_paragraph_order unique (newsletter_id, display_order)
);

create index if not exists idx_newsletters_published_at on newsletters(published_at);

comment on table newsletters is '뉴스레터 마스터';
comment on column newsletters.slug is '공개 URL용 슬러그';
comment on column newsletters.title is '뉴스레터 제목';
comment on column newsletters.category_label is '관리 화면 카테고리 라벨';
comment on column newsletters.published_at is '게시일';
comment on column newsletters.image_url is '대표 이미지 URL';
comment on column newsletters.summary is '목록/공유용 요약';
comment on column newsletters.created_at is '생성 시각';
comment on column newsletters.updated_at is '마지막 수정 시각';

comment on table newsletter_tags is '뉴스레터 태그';
comment on column newsletter_tags.newsletter_id is 'FK → newsletters.id';
comment on column newsletter_tags.display_order is '표시 순서';
comment on column newsletter_tags.tag_name is '태그 문자열';
comment on column newsletter_tags.created_at is '생성 시각';
comment on column newsletter_tags.updated_at is '마지막 수정 시각';

comment on table newsletter_paragraphs is '뉴스레터 본문 문단';
comment on column newsletter_paragraphs.newsletter_id is 'FK → newsletters.id';
comment on column newsletter_paragraphs.display_order is '문단 순서';
comment on column newsletter_paragraphs.body is '본문 문단';
comment on column newsletter_paragraphs.created_at is '생성 시각';
comment on column newsletter_paragraphs.updated_at is '마지막 수정 시각';
