-- =============================================================================
-- V17 (PostgreSQL) - 운영 보정용 누락 테이블 복구
-- =============================================================================
-- 배경
--   일부 PostgreSQL 환경은 flyway_schema_history 상으로는 V16까지 반영된 것처럼
--   보이지만, 실제 운영 보조 테이블(admin/webzine/newsletter/subscription)이
--   누락된 상태일 수 있다.
--
-- 목적
--   1. 누락된 후속 관리 테이블을 안전하게 복구한다.
--   2. 이미 존재하는 테이블과 충돌하지 않도록 모두 IF NOT EXISTS로 생성한다.
--   3. 복구 마이그레이션은 "구조 복원"에 집중하고, 강한 FK는 후속 마이그레이션에서
--      점진적으로 보강할 수 있게 한다.
--
-- 주의
--   admin_audit_logs.admin_user_id는 의도적으로 users FK를 두지 않는다.
--   운영 DB가 부분 동기화 상태일 수 있어, 이 단계에서는 부팅 가능 상태를 먼저
--   복원하고 이후 정합성 마이그레이션에서 FK를 추가하는 전략을 택한다.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- 관리자 감사 로그
-- 운영 추적성 확보를 위한 핵심 테이블. 관리자 행위 이력의 최소 단위를 보존한다.
-- -----------------------------------------------------------------------------
create table if not exists admin_audit_logs (
    id bigint generated always as identity primary key,
    admin_user_id bigint not null,
    action_code varchar(64) not null,
    target_type varchar(64) not null,
    target_id bigint,
    detail varchar(2000),
    created_at timestamp(6) not null
);

create index if not exists idx_admin_audit_logs_created_at on admin_audit_logs (created_at desc);
create index if not exists idx_admin_audit_logs_admin_user on admin_audit_logs (admin_user_id);

comment on table admin_audit_logs is '관리자 주요 행위에 대한 감사 로그';
comment on column admin_audit_logs.id is '감사 로그 PK';
comment on column admin_audit_logs.admin_user_id is '행위를 수행한 관리자 식별자. 운영 복구 단계에서는 FK를 지연 적용한다';
comment on column admin_audit_logs.action_code is '행위 코드. 예: RESERVATION_CANCEL, ISSUE_CREATE';
comment on column admin_audit_logs.target_type is '대상 도메인 유형. 예: RESERVATION, WEBZINE_ISSUE';
comment on column admin_audit_logs.target_id is '대상 엔티티 식별자';
comment on column admin_audit_logs.detail is '추가 설명 또는 JSON 스냅샷';
comment on column admin_audit_logs.created_at is '감사 로그 생성 시각';
comment on index idx_admin_audit_logs_created_at is '최신 감사 로그 목록 조회 최적화';
comment on index idx_admin_audit_logs_admin_user is '관리자별 감사 로그 조회 최적화';

-- -----------------------------------------------------------------------------
-- 웹진 호
-- 호 단위 메타데이터를 보관하며, 기사의 루트 aggregate 역할을 한다.
-- -----------------------------------------------------------------------------
create table if not exists webzine_issues (
    id bigint generated by default as identity primary key,
    slug varchar(80) not null,
    volume integer not null,
    issue_date date not null,
    cover_image_url varchar(500) not null,
    teaser varchar(1000) not null,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,
    constraint uk_webzine_issue_slug unique (slug),
    constraint uk_webzine_issue_volume unique (volume)
);

comment on table webzine_issues is '웹진 호 메타데이터';
comment on column webzine_issues.slug is '호 공개 slug';
comment on column webzine_issues.volume is '발행 호수';
comment on column webzine_issues.issue_date is '발행일';
comment on column webzine_issues.cover_image_url is '호 표지 이미지 URL';
comment on column webzine_issues.teaser is '호 소개 문구';

-- -----------------------------------------------------------------------------
-- 웹진 기사
-- 호에 속한 개별 기사. 카드/상세 렌더링에 필요한 핵심 메타를 가진다.
-- -----------------------------------------------------------------------------
create table if not exists webzine_articles (
    id bigint generated by default as identity primary key,
    issue_id bigint not null references webzine_issues(id) on delete cascade,
    slug varchar(150) not null,
    title varchar(200) not null,
    kicker varchar(200) not null,
    summary text not null,
    hero_image_url varchar(500) not null,
    card_image_url varchar(500) not null,
    category varchar(30) not null,
    format_label varchar(60) not null,
    author_name varchar(120) not null,
    author_email varchar(255) not null,
    credit_line varchar(255) not null,
    highlight_quote varchar(500),
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,
    constraint uk_webzine_article_issue_slug unique (issue_id, slug)
);

create index if not exists idx_webzine_articles_issue_id on webzine_articles(issue_id);

comment on table webzine_articles is '웹진 기사 메타데이터';
comment on column webzine_articles.issue_id is '소속 웹진 호 FK';
comment on column webzine_articles.slug is '기사 공개 slug';
comment on column webzine_articles.title is '기사 제목';
comment on column webzine_articles.kicker is '카테고리성 보조 제목';
comment on column webzine_articles.summary is '목록/공유용 요약';
comment on column webzine_articles.hero_image_url is '상세 상단 대표 이미지 URL';
comment on column webzine_articles.card_image_url is '카드 목록용 이미지 URL';
comment on column webzine_articles.category is '기사 분류';
comment on column webzine_articles.format_label is '아티클 형식 라벨';
comment on column webzine_articles.author_name is '작성자명';
comment on column webzine_articles.author_email is '작성자 연락 이메일';
comment on column webzine_articles.credit_line is '크레딧 라인';
comment on column webzine_articles.highlight_quote is '강조 인용문';
comment on index idx_webzine_articles_issue_id is '호별 기사 목록 조회 최적화';

-- -----------------------------------------------------------------------------
-- 웹진 기사 본문 섹션
-- 상세 페이지 본문을 순서형 블록으로 관리한다.
-- -----------------------------------------------------------------------------
create table if not exists webzine_article_sections (
    id bigint generated by default as identity primary key,
    article_id bigint not null references webzine_articles(id) on delete cascade,
    display_order integer not null,
    heading varchar(200),
    body text not null,
    note varchar(1000),
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,
    constraint uk_webzine_article_section_order unique (article_id, display_order)
);

comment on table webzine_article_sections is '웹진 기사 본문 섹션';
comment on column webzine_article_sections.article_id is '소속 기사 FK';
comment on column webzine_article_sections.display_order is '본문 표시 순서';
comment on column webzine_article_sections.heading is '섹션 제목';
comment on column webzine_article_sections.body is '본문 내용';
comment on column webzine_article_sections.note is '보충 메모 또는 각주';

-- -----------------------------------------------------------------------------
-- 웹진 기사 갤러리
-- 상세 하단 이미지 묶음을 순서형으로 관리한다.
-- -----------------------------------------------------------------------------
create table if not exists webzine_article_gallery_images (
    id bigint generated by default as identity primary key,
    article_id bigint not null references webzine_articles(id) on delete cascade,
    display_order integer not null,
    image_url varchar(500) not null,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,
    constraint uk_webzine_article_gallery_order unique (article_id, display_order)
);

comment on table webzine_article_gallery_images is '웹진 기사 상세 갤러리 이미지';
comment on column webzine_article_gallery_images.article_id is '소속 기사 FK';
comment on column webzine_article_gallery_images.display_order is '갤러리 이미지 표시 순서';
comment on column webzine_article_gallery_images.image_url is '갤러리 이미지 URL';

-- -----------------------------------------------------------------------------
-- 웹진 기사 태그
-- 상세/목록/검색 보조를 위한 태그 컬렉션이다.
-- -----------------------------------------------------------------------------
create table if not exists webzine_article_tags (
    id bigint generated by default as identity primary key,
    article_id bigint not null references webzine_articles(id) on delete cascade,
    display_order integer not null,
    tag_name varchar(80) not null,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,
    constraint uk_webzine_article_tag_name unique (article_id, tag_name)
);

comment on table webzine_article_tags is '웹진 기사 태그';
comment on column webzine_article_tags.article_id is '소속 기사 FK';
comment on column webzine_article_tags.display_order is '태그 표시 순서';
comment on column webzine_article_tags.tag_name is '태그 문자열';

-- -----------------------------------------------------------------------------
-- 소식지 마스터
-- 소식지 목록/상세 관리의 루트 엔티티 테이블이다.
-- -----------------------------------------------------------------------------
create table if not exists newsletters (
    id bigint generated by default as identity primary key,
    slug varchar(160) not null,
    title varchar(200) not null,
    category_label varchar(80) not null,
    published_at date not null,
    image_url varchar(500) not null,
    summary text not null,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,
    constraint uk_newsletter_slug unique (slug)
);

comment on table newsletters is '소식지 마스터';
comment on column newsletters.slug is '소식지 공개 slug';
comment on column newsletters.title is '소식지 제목';
comment on column newsletters.category_label is '관리 화면 분류 라벨';
comment on column newsletters.published_at is '게시일';
comment on column newsletters.image_url is '대표 이미지 URL';
comment on column newsletters.summary is '목록/공유용 요약';

-- -----------------------------------------------------------------------------
-- 소식지 태그
-- 목록/상세 노출용 태그 집합이다.
-- -----------------------------------------------------------------------------
create table if not exists newsletter_tags (
    id bigint generated by default as identity primary key,
    newsletter_id bigint not null references newsletters(id) on delete cascade,
    display_order integer not null,
    tag_name varchar(80) not null,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,
    constraint uk_newsletter_tag_name unique (newsletter_id, tag_name)
);

comment on table newsletter_tags is '소식지 태그';
comment on column newsletter_tags.newsletter_id is '소속 소식지 FK';
comment on column newsletter_tags.display_order is '태그 표시 순서';
comment on column newsletter_tags.tag_name is '태그 문자열';

-- -----------------------------------------------------------------------------
-- 소식지 본문 문단
-- 상세 페이지 본문을 순서형 문단으로 관리한다.
-- -----------------------------------------------------------------------------
create table if not exists newsletter_paragraphs (
    id bigint generated by default as identity primary key,
    newsletter_id bigint not null references newsletters(id) on delete cascade,
    display_order integer not null,
    body text not null,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,
    constraint uk_newsletter_paragraph_order unique (newsletter_id, display_order)
);

create index if not exists idx_newsletters_published_at on newsletters (published_at);

comment on table newsletter_paragraphs is '소식지 본문 문단';
comment on column newsletter_paragraphs.newsletter_id is '소속 소식지 FK';
comment on column newsletter_paragraphs.display_order is '문단 표시 순서';
comment on column newsletter_paragraphs.body is '본문 문단 내용';
comment on index idx_newsletters_published_at is '게시일 기준 소식지 정렬 최적화';

-- -----------------------------------------------------------------------------
-- 이메일 구독
-- 구독 대상과 동의 이력을 함께 보관한다.
-- -----------------------------------------------------------------------------
create table if not exists email_subscriptions (
    id bigint generated by default as identity primary key,
    email varchar(255) not null,
    subscribed_newsletters boolean not null default true,
    subscribed_issues boolean not null default true,
    consented_at timestamp not null,
    subscribed_at timestamp not null,
    subscription_source varchar(50) not null,
    active boolean not null default true,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,
    constraint uk_email_subscriptions_email unique (email)
);

comment on table email_subscriptions is '이메일 구독 마스터';
comment on column email_subscriptions.email is '구독 이메일';
comment on column email_subscriptions.subscribed_newsletters is '소식지 수신 여부';
comment on column email_subscriptions.subscribed_issues is '호별보기 수신 여부';
comment on column email_subscriptions.consented_at is '개인정보 수집 및 활용 동의 시각';
comment on column email_subscriptions.subscribed_at is '구독 등록 시각';
comment on column email_subscriptions.subscription_source is '구독 유입 채널';
comment on column email_subscriptions.active is '활성 구독 여부';

-- -----------------------------------------------------------------------------
-- 발송 이력
-- 실제 메일 발송 엔진이 아니라도 "무엇을 누구에게 보냈는지"를 추적할 수 있게 한다.
-- -----------------------------------------------------------------------------
create table if not exists subscription_dispatch_histories (
    id bigint generated by default as identity primary key,
    content_type varchar(40) not null,
    content_slug varchar(160) not null,
    content_title varchar(255) not null,
    content_summary varchar(1000),
    dispatch_channel varchar(20) not null,
    dispatch_status varchar(20) not null,
    recipient_count bigint not null,
    content_created_at timestamp,
    dispatched_at timestamp not null,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,
    constraint uk_subscription_dispatch_content unique (content_type, content_slug, dispatch_channel)
);

create index if not exists idx_email_subscriptions_active on email_subscriptions(active);
create index if not exists idx_subscription_dispatch_histories_dispatched_at
    on subscription_dispatch_histories(dispatched_at);

comment on table subscription_dispatch_histories is '구독 콘텐츠 발송 이력';
comment on column subscription_dispatch_histories.content_type is '콘텐츠 유형. 예: NEWSLETTER, WEBZINE_ISSUE';
comment on column subscription_dispatch_histories.content_slug is '발송된 콘텐츠 slug';
comment on column subscription_dispatch_histories.content_title is '발송 시점의 콘텐츠 제목 스냅샷';
comment on column subscription_dispatch_histories.content_summary is '발송 시점의 요약 스냅샷';
comment on column subscription_dispatch_histories.dispatch_channel is '발송 채널. 현재 EMAIL';
comment on column subscription_dispatch_histories.dispatch_status is '발송 상태 또는 기록 상태';
comment on column subscription_dispatch_histories.recipient_count is '수신자 수';
comment on column subscription_dispatch_histories.content_created_at is '원본 콘텐츠 생성 시각';
comment on column subscription_dispatch_histories.dispatched_at is '발송 또는 기록 시각';
comment on index idx_email_subscriptions_active is '활성 구독자 조회 최적화';
comment on index idx_subscription_dispatch_histories_dispatched_at is '최신 발송 이력 조회 최적화';
