-- =============================================================================
-- V1: 초기 스키마 (사용자·상품·예약·리뷰·이미지·설문·찜·일정)
-- =============================================================================

-- -----------------------------------------------------------------------------
-- users: 애플리케이션 회원
-- -----------------------------------------------------------------------------
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL,
    nickname VARCHAR(10) NOT NULL,
    role VARCHAR(255) NOT NULL,
    last_login_at TIMESTAMP,
    CONSTRAINT chk_users_role CHECK (role IN ('USER'))
);

CREATE INDEX idx_users_email ON users (email);

COMMENT ON TABLE users IS '서비스 회원. OAuth 연동은 user_oauths 참조';
COMMENT ON COLUMN users.id IS '회원 PK';
COMMENT ON COLUMN users.email IS '로그인·식별용 이메일(유니크 인덱스)';
COMMENT ON COLUMN users.nickname IS '표시 닉네임';
COMMENT ON COLUMN users.role IS '권한 역할(현재 USER만 허용)';
COMMENT ON COLUMN users.last_login_at IS '마지막 로그인 시각';

-- -----------------------------------------------------------------------------
-- user_oauths: OAuth 제공자별 계정 연결
-- -----------------------------------------------------------------------------
CREATE TABLE user_oauths (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    provider VARCHAR(255) NOT NULL,
    provider_id VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    CONSTRAINT chk_user_oauths_provider CHECK (provider IN ('GOOGLE', 'TEST'))
);

CREATE INDEX idx_user_oauths_user_id ON user_oauths (user_id);
CREATE INDEX idx_user_oauths_provider_provider_id ON user_oauths (provider, provider_id);
CREATE INDEX idx_user_oauths_email ON user_oauths (email);

COMMENT ON TABLE user_oauths IS '외부 OAuth 계정과 users 매핑';
COMMENT ON COLUMN user_oauths.id IS '연동 행 PK';
COMMENT ON COLUMN user_oauths.user_id IS 'users.id FK';
COMMENT ON COLUMN user_oauths.provider IS 'OAuth 제공자(GOOGLE, TEST)';
COMMENT ON COLUMN user_oauths.provider_id IS '제공자 측 사용자 식별자';
COMMENT ON COLUMN user_oauths.email IS '제공자가 넘긴 이메일';

-- -----------------------------------------------------------------------------
-- options: 상품에 붙는 옵션(가격·장소 등)
-- -----------------------------------------------------------------------------
CREATE TABLE options (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    description TEXT NOT NULL,
    price NUMERIC(38, 2) NOT NULL,
    location VARCHAR(200) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

COMMENT ON TABLE options IS '상품 옵션 마스터(가격·설명·위치 문구)';
COMMENT ON COLUMN options.id IS '옵션 PK';
COMMENT ON COLUMN options.name IS '옵션명';
COMMENT ON COLUMN options.description IS '옵션 상세 설명';
COMMENT ON COLUMN options.price IS '옵션 가격';
COMMENT ON COLUMN options.location IS '옵션 관련 위치 표시 문자열';
COMMENT ON COLUMN options.created_at IS '생성 시각';
COMMENT ON COLUMN options.updated_at IS '수정 시각';

-- -----------------------------------------------------------------------------
-- products: 상품 마스터
-- -----------------------------------------------------------------------------
CREATE TABLE products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    description TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

COMMENT ON TABLE products IS '상품 기본 정보';
COMMENT ON COLUMN products.id IS '상품 PK';
COMMENT ON COLUMN products.name IS '상품명';
COMMENT ON COLUMN products.description IS '상품 설명';
COMMENT ON COLUMN products.created_at IS '생성 시각';
COMMENT ON COLUMN products.updated_at IS '수정 시각';

-- -----------------------------------------------------------------------------
-- product_option: 상품-옵션 N:M
-- -----------------------------------------------------------------------------
CREATE TABLE product_option (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL,
    option_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_product_option UNIQUE (product_id, option_id),
    CONSTRAINT fk_product_option_product FOREIGN KEY (product_id) REFERENCES products (id),
    CONSTRAINT fk_product_option_option FOREIGN KEY (option_id) REFERENCES options (id)
);

CREATE INDEX idx_product_option_product_id ON product_option (product_id);
CREATE INDEX idx_product_option_option_id ON product_option (option_id);

COMMENT ON TABLE product_option IS '상품에 포함된 옵션 연결';
COMMENT ON COLUMN product_option.id IS '연결 행 PK';
COMMENT ON COLUMN product_option.product_id IS 'products.id FK';
COMMENT ON COLUMN product_option.option_id IS 'options.id FK';
COMMENT ON COLUMN product_option.created_at IS '생성 시각';
COMMENT ON COLUMN product_option.updated_at IS '수정 시각';

-- -----------------------------------------------------------------------------
-- product_tag: 상품 태그
-- -----------------------------------------------------------------------------
CREATE TABLE product_tag (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL,
    tag_name VARCHAR(50) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_product_tag UNIQUE (product_id, tag_name),
    CONSTRAINT fk_product_tag_product FOREIGN KEY (product_id) REFERENCES products (id)
);

CREATE INDEX idx_product_tag_tag_name ON product_tag (tag_name);
CREATE INDEX idx_product_tag_product_id ON product_tag (product_id);

COMMENT ON TABLE product_tag IS '상품별 검색·분류용 태그';
COMMENT ON COLUMN product_tag.id IS '태그 행 PK';
COMMENT ON COLUMN product_tag.product_id IS 'products.id FK';
COMMENT ON COLUMN product_tag.tag_name IS '태그 문자열';
COMMENT ON COLUMN product_tag.created_at IS '생성 시각';
COMMENT ON COLUMN product_tag.updated_at IS '수정 시각';

-- -----------------------------------------------------------------------------
-- product_locations: 상품 대표 위치(지도 1건)
-- -----------------------------------------------------------------------------
CREATE TABLE product_locations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL,
    name VARCHAR(120) NOT NULL,
    latitude NUMERIC(10, 7) NOT NULL,
    longitude NUMERIC(10, 7) NOT NULL,
    road_address_name VARCHAR(255),
    address_name VARCHAR(255),
    kakao_place_id VARCHAR(40) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_product_locations_product UNIQUE (product_id),
    CONSTRAINT fk_product_locations_product FOREIGN KEY (product_id) REFERENCES products (id)
);

COMMENT ON TABLE product_locations IS '상품당 하나의 지도/주소 정보';
COMMENT ON COLUMN product_locations.id IS '위치 행 PK';
COMMENT ON COLUMN product_locations.product_id IS 'products.id FK';
COMMENT ON COLUMN product_locations.name IS '장소 표시명';
COMMENT ON COLUMN product_locations.latitude IS '위도';
COMMENT ON COLUMN product_locations.longitude IS '경도';
COMMENT ON COLUMN product_locations.road_address_name IS '도로명 주소';
COMMENT ON COLUMN product_locations.address_name IS '지번/일반 주소';
COMMENT ON COLUMN product_locations.kakao_place_id IS '카카오 장소 ID';
COMMENT ON COLUMN product_locations.created_at IS '생성 시각';
COMMENT ON COLUMN product_locations.updated_at IS '수정 시각';

-- -----------------------------------------------------------------------------
-- reservation_slots: 상품별 예약 가능 슬롯(날짜·시간대)
-- -----------------------------------------------------------------------------
CREATE TABLE reservation_slots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL,
    reservation_date DATE NOT NULL,
    start_time TIME NOT NULL,
    end_time TIME NOT NULL,
    is_booked BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_reservation_slot_product_date_start UNIQUE (product_id, reservation_date, start_time),
    CONSTRAINT fk_reservation_slots_product FOREIGN KEY (product_id) REFERENCES products (id),
    CONSTRAINT chk_reservation_slots_time CHECK (end_time > start_time)
);

CREATE INDEX idx_reservation_slots_product_id ON reservation_slots (product_id);

COMMENT ON TABLE reservation_slots IS '예약 가능 시간 슬롯';
COMMENT ON COLUMN reservation_slots.id IS '슬롯 PK';
COMMENT ON COLUMN reservation_slots.product_id IS 'products.id FK';
COMMENT ON COLUMN reservation_slots.reservation_date IS '슬롯 날짜';
COMMENT ON COLUMN reservation_slots.start_time IS '시작 시각';
COMMENT ON COLUMN reservation_slots.end_time IS '종료 시각(시작보다 커야 함)';
COMMENT ON COLUMN reservation_slots.is_booked IS '예약 확정 등으로 점유 여부';
COMMENT ON COLUMN reservation_slots.created_at IS '생성 시각';
COMMENT ON COLUMN reservation_slots.updated_at IS '수정 시각';

-- -----------------------------------------------------------------------------
-- reservations: 사용자 예약(슬롯·상태·금액)
-- -----------------------------------------------------------------------------
CREATE TABLE reservations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reservation_slot_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    visit_date DATE NOT NULL,
    visit_start_time TIME NOT NULL,
    visit_end_time TIME NOT NULL,
    total_price NUMERIC(15, 2) NOT NULL,
    status VARCHAR(20) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_reservations_reservation_slot FOREIGN KEY (reservation_slot_id) REFERENCES reservation_slots (id),
    CONSTRAINT chk_reservations_status CHECK (status IN ('PREBOOK', 'PENDING', 'BOOKED', 'COMPLETED', 'CANCELED'))
);

CREATE INDEX idx_reservations_user_visit_time ON reservations (user_id, visit_date, visit_start_time);
CREATE INDEX idx_reservations_reservation_slot_id ON reservations (reservation_slot_id);

COMMENT ON TABLE reservations IS '회원의 예약 건';
COMMENT ON COLUMN reservations.id IS '예약 PK';
COMMENT ON COLUMN reservations.reservation_slot_id IS 'reservation_slots.id FK';
COMMENT ON COLUMN reservations.user_id IS '예약자 users.id';
COMMENT ON COLUMN reservations.visit_date IS '방문일';
COMMENT ON COLUMN reservations.visit_start_time IS '방문 시작 시각';
COMMENT ON COLUMN reservations.visit_end_time IS '방문 종료 시각';
COMMENT ON COLUMN reservations.total_price IS '예약 총액';
COMMENT ON COLUMN reservations.status IS '예약 상태(PREBOOK/PENDING/BOOKED/COMPLETED/CANCELED)';
COMMENT ON COLUMN reservations.created_at IS '생성 시각';
COMMENT ON COLUMN reservations.updated_at IS '수정 시각';

-- -----------------------------------------------------------------------------
-- product_reviews: 상품 리뷰(회원당 1건)
-- -----------------------------------------------------------------------------
CREATE TABLE product_reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    rating INT NOT NULL,
    content VARCHAR(2000) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_product_review_user UNIQUE (product_id, user_id),
    CONSTRAINT fk_product_reviews_product FOREIGN KEY (product_id) REFERENCES products (id),
    CONSTRAINT chk_product_reviews_rating CHECK (rating BETWEEN 1 AND 5)
);

CREATE INDEX idx_product_reviews_product_id ON product_reviews (product_id);
CREATE INDEX idx_product_reviews_user_id ON product_reviews (user_id);

COMMENT ON TABLE product_reviews IS '상품별 사용자 리뷰(상품·사용자 유니크)';
COMMENT ON COLUMN product_reviews.id IS '리뷰 PK';
COMMENT ON COLUMN product_reviews.product_id IS 'products.id FK';
COMMENT ON COLUMN product_reviews.user_id IS '작성자 users.id';
COMMENT ON COLUMN product_reviews.rating IS '별점 1~5';
COMMENT ON COLUMN product_reviews.content IS '리뷰 본문';
COMMENT ON COLUMN product_reviews.created_at IS '생성 시각';
COMMENT ON COLUMN product_reviews.updated_at IS '수정 시각';

-- -----------------------------------------------------------------------------
-- images: 집계 타입별 첨부 이미지
-- -----------------------------------------------------------------------------
CREATE TABLE images (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aggregate_type VARCHAR(30) NOT NULL,
    aggregate_id BIGINT NOT NULL,
    original_filename VARCHAR(255) NOT NULL,
    unique_filename VARCHAR(255) NOT NULL,
    extension VARCHAR(20) NOT NULL,
    file_size BIGINT NOT NULL,
    url VARCHAR(500) NOT NULL,
    sort_order INT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT chk_images_aggregate_type CHECK (aggregate_type IN ('PRODUCT', 'OPTION', 'USER', 'PRODUCT_REVIEW')),
    CONSTRAINT chk_images_sort_order CHECK (sort_order >= 0),
    CONSTRAINT chk_images_file_size CHECK (file_size > 0)
);

CREATE INDEX idx_images_aggregate ON images (aggregate_type, aggregate_id, sort_order);

COMMENT ON TABLE images IS '도메인 엔티티별 저장 이미지 메타';
COMMENT ON COLUMN images.id IS '이미지 PK';
COMMENT ON COLUMN images.aggregate_type IS '소속 엔티티 종류';
COMMENT ON COLUMN images.aggregate_id IS '소속 엔티티 PK';
COMMENT ON COLUMN images.original_filename IS '업로드 원본 파일명';
COMMENT ON COLUMN images.unique_filename IS '저장용 유니크 파일명';
COMMENT ON COLUMN images.extension IS '확장자';
COMMENT ON COLUMN images.file_size IS '파일 크기(바이트, 양수)';
COMMENT ON COLUMN images.url IS '접근 URL';
COMMENT ON COLUMN images.sort_order IS '같은 aggregate 내 정렬 순서(0 이상)';
COMMENT ON COLUMN images.created_at IS '생성 시각';
COMMENT ON COLUMN images.updated_at IS '수정 시각';

-- -----------------------------------------------------------------------------
-- user_survey: 온보딩/취향 설문(회원당 1건)
-- -----------------------------------------------------------------------------
CREATE TABLE user_survey (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    concept VARCHAR(30) NOT NULL,
    idol_name VARCHAR(255) NOT NULL,
    visit_start_date DATE NOT NULL,
    visit_end_date DATE NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_user_survey_user_id UNIQUE (user_id),
    CONSTRAINT fk_user_survey_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT chk_user_survey_concept CHECK (concept IN ('GIRL_CRUSH', 'LOVELY_FRESH', 'ELEGANT_GLAM', 'DREAMY', 'HIGHTEEN', 'ETC')),
    CONSTRAINT chk_user_survey_visit_dates CHECK (visit_end_date >= visit_start_date)
);

CREATE INDEX idx_user_survey_user_id ON user_survey (user_id);

COMMENT ON TABLE user_survey IS '사용자 설문(콘셉트·아이돌명·방문 기간)';
COMMENT ON COLUMN user_survey.id IS '설문 PK';
COMMENT ON COLUMN user_survey.user_id IS 'users.id FK';
COMMENT ON COLUMN user_survey.concept IS '선호 콘셉트 코드';
COMMENT ON COLUMN user_survey.idol_name IS '관심 아이돌/그룹명';
COMMENT ON COLUMN user_survey.visit_start_date IS '방문 희망 시작일';
COMMENT ON COLUMN user_survey.visit_end_date IS '방문 희망 종료일';
COMMENT ON COLUMN user_survey.created_at IS '생성 시각';
COMMENT ON COLUMN user_survey.updated_at IS '수정 시각';

-- -----------------------------------------------------------------------------
-- user_survey_places: 설문에 선택한 장소 목록
-- -----------------------------------------------------------------------------
CREATE TABLE user_survey_places (
    user_survey_id BIGINT NOT NULL,
    place VARCHAR(100) NOT NULL,
    CONSTRAINT fk_user_survey_places_survey FOREIGN KEY (user_survey_id) REFERENCES user_survey (id)
);

CREATE INDEX idx_user_survey_places_survey_id ON user_survey_places (user_survey_id);

COMMENT ON TABLE user_survey_places IS '설문에 기입한 방문 희망 장소(복수 행)';
COMMENT ON COLUMN user_survey_places.user_survey_id IS 'user_survey.id FK';
COMMENT ON COLUMN user_survey_places.place IS '장소명';

-- -----------------------------------------------------------------------------
-- wishes: 상품 찜(회원·상품 유니크)
-- -----------------------------------------------------------------------------
CREATE TABLE wishes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_user_product_wish UNIQUE (user_id, product_id),
    CONSTRAINT fk_wishes_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_wishes_product FOREIGN KEY (product_id) REFERENCES products (id)
);

CREATE INDEX idx_wishes_user_id ON wishes (user_id);
CREATE INDEX idx_wishes_product_id ON wishes (product_id);

COMMENT ON TABLE wishes IS '사용자의 상품 찜';
COMMENT ON COLUMN wishes.id IS '찜 PK';
COMMENT ON COLUMN wishes.user_id IS 'users.id FK';
COMMENT ON COLUMN wishes.product_id IS 'products.id FK';
COMMENT ON COLUMN wishes.created_at IS '생성 시각';
COMMENT ON COLUMN wishes.updated_at IS '수정 시각';

-- -----------------------------------------------------------------------------
-- schedules: 마이페이지 일정(상품 연동)
-- -----------------------------------------------------------------------------
CREATE TABLE schedules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    title VARCHAR(100) NOT NULL,
    start_at TIMESTAMP NOT NULL,
    end_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT chk_schedules_time CHECK (end_at >= start_at)
);

CREATE INDEX idx_schedule_user_start ON schedules (user_id, start_at);

COMMENT ON TABLE schedules IS '사용자 일정(상품 참조)';
COMMENT ON COLUMN schedules.id IS '일정 PK';
COMMENT ON COLUMN schedules.user_id IS 'users.id';
COMMENT ON COLUMN schedules.product_id IS 'products.id';
COMMENT ON COLUMN schedules.title IS '일정 제목';
COMMENT ON COLUMN schedules.start_at IS '시작 시각';
COMMENT ON COLUMN schedules.end_at IS '종료 시각(시작 이상)';
COMMENT ON COLUMN schedules.created_at IS '생성 시각';
COMMENT ON COLUMN schedules.updated_at IS '수정 시각';
