-- =============================================================================
-- Flyway V23 (PostgreSQL) - 인증 검증 감사 로그
-- =============================================================================
-- 목적
--   가입·비밀번호 찾기 등 이메일/계정 검증 시도를 한 행으로 남긴다.
--   AuthVerificationAuditLog 엔티티 테이블명 auth_verification_audit_logs 와 일치한다.
--   운영 추적·남용 탐지에 사용하며 관리자 API에서 유형·키워드로 조회한다.
-- 인덱스
--   created_at DESC: 최근 로그 페이지
--   verification_type, created_at DESC: 유형 필터 + 최신순
-- =============================================================================

create table if not exists auth_verification_audit_logs (
    id                 bigint        not null generated by default as identity primary key,
    verification_type  varchar(64)   not null,
    email              varchar(190),
    username           varchar(120),
    ip_address         varchar(64)   not null,
    success            boolean       not null,
    detail             varchar(500),
    created_at         timestamp(6)  not null
);

create index if not exists idx_auth_verification_audit_logs_created_at
    on auth_verification_audit_logs (created_at desc);

create index if not exists idx_auth_verification_audit_logs_type_created
    on auth_verification_audit_logs (verification_type, created_at desc);

COMMENT ON TABLE auth_verification_audit_logs IS '인증·검증(이메일 코드 등) 시도 감사 로그';
COMMENT ON COLUMN auth_verification_audit_logs.id IS '로그 PK 자동 증가';
COMMENT ON COLUMN auth_verification_audit_logs.verification_type IS '검증 유형 코드(서비스에서 정의한 문자열, 예: SIGNUP_EMAIL)';
COMMENT ON COLUMN auth_verification_audit_logs.email IS '시도에 사용된 이메일 주소';
COMMENT ON COLUMN auth_verification_audit_logs.username IS '시도에 사용된 사용자명 또는 닉네임';
COMMENT ON COLUMN auth_verification_audit_logs.ip_address IS '요청 클라이언트 IP 주소';
COMMENT ON COLUMN auth_verification_audit_logs.success IS '검증 성공 여부(true 성공, false 실패)';
COMMENT ON COLUMN auth_verification_audit_logs.detail IS '실패 사유·메모 등 부가 설명(최대 500자)';
COMMENT ON COLUMN auth_verification_audit_logs.created_at IS '로그가 기록된 시각';

COMMENT ON INDEX idx_auth_verification_audit_logs_created_at IS '최근 검증 시도 목록 조회용';
COMMENT ON INDEX idx_auth_verification_audit_logs_type_created IS '유형별 최근 시도 조회용';
