-- =============================================================================
-- Flyway V24  - 가입·계정 검증 토큰
-- =============================================================================
-- 목적
--   이메일 가입 인증, 계정 확인 등 일회성 토큰을 저장한다.
--   SignupVerificationToken 엔티티 테이블명 signup_verification_tokens 와 일치한다.
-- 인덱스
--   uk_signup_verification_tokens_token: findByToken
--   idx_signup_verification_tokens_email_type_status_created: 최신 PENDING 등 조회
-- =============================================================================

create table if not exists signup_verification_tokens (
    id             bigint        not null generated by default as identity primary key,
    token          varchar(120)  not null,
    type           varchar(40)   not null,
    email          varchar(190)  not null,
    username       varchar(120),
    user_id        bigint,
    status         varchar(30)   not null,
    requested_ip   varchar(64)   not null,
    confirmed_ip   varchar(64),
    expires_at     timestamp(6)  not null,
    created_at     timestamp(6)  not null,
    confirmed_at   timestamp(6),
    detail         varchar(500),
    constraint uk_signup_verification_tokens_token unique (token)
);

create index if not exists idx_signup_verification_tokens_email_type_status_created
    on signup_verification_tokens (email, type, status, created_at desc);

COMMENT ON TABLE signup_verification_tokens IS '가입·계정 확인용 검증 토큰 저장소';
COMMENT ON COLUMN signup_verification_tokens.id IS '행 PK';
COMMENT ON COLUMN signup_verification_tokens.token IS '클라이언트에 전달하는 불투명 토큰(유일)';
COMMENT ON COLUMN signup_verification_tokens.type IS '검증 유형(EMAIL_SIGNUP_VERIFY, ACCOUNT_CONFIRM 등)';
COMMENT ON COLUMN signup_verification_tokens.email IS '검증 대상 이메일';
COMMENT ON COLUMN signup_verification_tokens.username IS '표시용 사용자명·닉네임(있을 때만)';
COMMENT ON COLUMN signup_verification_tokens.user_id IS '검증 완료 후 매핑된 사용자 PK';
COMMENT ON COLUMN signup_verification_tokens.status IS 'PENDING, VERIFIED, USED, REJECTED, EXPIRED';
COMMENT ON COLUMN signup_verification_tokens.requested_ip IS '토큰 발급 요청 IP';
COMMENT ON COLUMN signup_verification_tokens.confirmed_ip IS '토큰 검증 요청 IP';
COMMENT ON COLUMN signup_verification_tokens.expires_at IS '토큰 만료 시각';
COMMENT ON COLUMN signup_verification_tokens.created_at IS '레코드 생성 시각';
COMMENT ON COLUMN signup_verification_tokens.confirmed_at IS '검증 또는 사용 처리 시각';
COMMENT ON COLUMN signup_verification_tokens.detail IS '실패·거절 시 부가 설명';

COMMENT ON INDEX idx_signup_verification_tokens_email_type_status_created IS '이메일·유형·상태별 최신 토큰 조회용';
