-- ============================================================================
-- V2 통합 마이그레이션 (PostgreSQL)
-- ----------------------------------------------------------------------------
-- 목적
--   1) products.base_price 컬럼 누락 시 idempotent 보정
--   2) 문항형 설문(Form → Question → Option / Submission → Answer) 스키마 도입
--   3) 상품 추천 운영 플래그/점수 + latest-in-korea 수동 큐레이션 테이블
--
-- 설계 메모
--   - CREATE IF NOT EXISTS 로 신규/기존 배포 모두 안전
--   - 설문 정규화: 관리자 문항 편집·응답 이력·통계/추천 확장에 대응
--   - 추천 컬럼·latest-korea 테이블: idempotent ADD + 백필 후 NOT NULL
-- ============================================================================

-- ----------------------------------------------------------------------------
-- [A] products — 가격 컬럼
-- ----------------------------------------------------------------------------

ALTER TABLE products
    ADD COLUMN IF NOT EXISTS base_price NUMERIC(19, 2) NOT NULL DEFAULT 0;

COMMENT ON COLUMN products.base_price IS '상품 기본가(옵션 합산과 별도)';

-- ----------------------------------------------------------------------------
-- [A2] products — 추천 운영 컬럼 + latest-in-korea 큐레이션
-- ----------------------------------------------------------------------------

ALTER TABLE products
    ADD COLUMN IF NOT EXISTS is_recommended BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE products
    ADD COLUMN IF NOT EXISTS recommendation_score INT NOT NULL DEFAULT 0;

UPDATE products SET is_recommended = COALESCE(is_recommended, FALSE);
UPDATE products SET recommendation_score = COALESCE(recommendation_score, 0);
ALTER TABLE products ALTER COLUMN is_recommended SET DEFAULT FALSE;
ALTER TABLE products ALTER COLUMN recommendation_score SET DEFAULT 0;
ALTER TABLE products ALTER COLUMN is_recommended SET NOT NULL;
ALTER TABLE products ALTER COLUMN recommendation_score SET NOT NULL;

COMMENT ON COLUMN products.is_recommended IS '관리자 추천 노출 여부';
COMMENT ON COLUMN products.recommendation_score IS '관리자 수동 추천 점수(높을수록 우선)';

CREATE TABLE IF NOT EXISTS product_latest_korea_recommendation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    display_order INT NOT NULL,
    product_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_latest_korea_product
        FOREIGN KEY (product_id)
        REFERENCES products(id)
        ON DELETE CASCADE,
    CONSTRAINT uk_latest_korea_display_order UNIQUE (display_order),
    CONSTRAINT uk_latest_korea_product_id UNIQUE (product_id)
);

COMMENT ON TABLE product_latest_korea_recommendation IS 'latest-in-korea 추천 상품 수동 큐레이션 순서';
COMMENT ON COLUMN product_latest_korea_recommendation.display_order IS '화면 노출 순서(1부터 증가)';
COMMENT ON COLUMN product_latest_korea_recommendation.product_id IS '추천 대상 상품 ID';

CREATE INDEX IF NOT EXISTS idx_latest_korea_product_id
    ON product_latest_korea_recommendation(product_id);

-- ----------------------------------------------------------------------------
-- [B] structured survey — 테이블 DDL (의존 순서)
-- ----------------------------------------------------------------------------

-- survey_form: 설문 템플릿(제목·설명·활성). active 로 버전 전환 운영 가능.
CREATE TABLE IF NOT EXISTS survey_form (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(200) NOT NULL,
    description TEXT,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

-- survey_question: 문항 정의(순서·타입·필수). form 삭제 시 CASCADE.
CREATE TABLE IF NOT EXISTS survey_question (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    survey_form_id BIGINT NOT NULL,
    display_order INT NOT NULL,
    title VARCHAR(300) NOT NULL,
    description TEXT,
    question_type VARCHAR(30) NOT NULL,
    required BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_survey_question_form
        FOREIGN KEY (survey_form_id)
        REFERENCES survey_form (id)
        ON DELETE CASCADE
);

-- survey_question_option: 객관식 선택지. display_order 로 UI 순서 고정.
CREATE TABLE IF NOT EXISTS survey_question_option (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    survey_question_id BIGINT NOT NULL,
    display_order INT NOT NULL,
    option_text VARCHAR(300) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_survey_question_option_question
        FOREIGN KEY (survey_question_id)
        REFERENCES survey_question (id)
        ON DELETE CASCADE
);

-- survey_submission: 사용자 1회 제출 헤더(form + user FK).
CREATE TABLE IF NOT EXISTS survey_submission (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    survey_form_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_survey_submission_form
        FOREIGN KEY (survey_form_id)
        REFERENCES survey_form (id)
        ON DELETE CASCADE,
    CONSTRAINT fk_survey_submission_user
        FOREIGN KEY (user_id)
        REFERENCES users (id)
        ON DELETE CASCADE
);

-- survey_answer: 문항별 응답 본문(TEXT는 answer_text, 객관식은 answer_option 확장).
CREATE TABLE IF NOT EXISTS survey_answer (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    survey_submission_id BIGINT NOT NULL,
    survey_question_id BIGINT NOT NULL,
    answer_text TEXT,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_survey_answer_submission
        FOREIGN KEY (survey_submission_id)
        REFERENCES survey_submission (id)
        ON DELETE CASCADE,
    CONSTRAINT fk_survey_answer_question
        FOREIGN KEY (survey_question_id)
        REFERENCES survey_question (id)
        ON DELETE CASCADE
);

-- survey_answer_option: 객관식·복수선택 스냅샷(option_text).
CREATE TABLE IF NOT EXISTS survey_answer_option (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    survey_answer_id BIGINT NOT NULL,
    display_order INT NOT NULL,
    option_text VARCHAR(300) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_survey_answer_option_answer
        FOREIGN KEY (survey_answer_id)
        REFERENCES survey_answer (id)
        ON DELETE CASCADE
);

-- ----------------------------------------------------------------------------
-- [C] structured survey — 테이블·컬럼 코멘트
-- ----------------------------------------------------------------------------

COMMENT ON TABLE survey_form IS '설문지 메타 정보(제목/설명/활성 상태)';
COMMENT ON COLUMN survey_form.id IS '설문지 PK';
COMMENT ON COLUMN survey_form.title IS '설문지 제목';
COMMENT ON COLUMN survey_form.description IS '설문지 설명';
COMMENT ON COLUMN survey_form.active IS '활성화 여부(true=현재 운영 설문)';
COMMENT ON COLUMN survey_form.created_at IS '생성 시각';
COMMENT ON COLUMN survey_form.updated_at IS '수정 시각';

COMMENT ON TABLE survey_question IS '설문지에 속한 문항 정의';
COMMENT ON COLUMN survey_question.id IS '문항 PK';
COMMENT ON COLUMN survey_question.survey_form_id IS '소속 설문지 ID(FK)';
COMMENT ON COLUMN survey_question.display_order IS '설문 화면 노출 순서';
COMMENT ON COLUMN survey_question.title IS '문항 제목';
COMMENT ON COLUMN survey_question.description IS '문항 부가 설명';
COMMENT ON COLUMN survey_question.question_type IS '문항 타입(TEXT/SINGLE_CHOICE/MULTIPLE_CHOICE)';
COMMENT ON COLUMN survey_question.required IS '필수 응답 여부';
COMMENT ON COLUMN survey_question.created_at IS '생성 시각';
COMMENT ON COLUMN survey_question.updated_at IS '수정 시각';

COMMENT ON TABLE survey_question_option IS '객관식 문항의 선택지 집합';
COMMENT ON COLUMN survey_question_option.id IS '선택지 PK';
COMMENT ON COLUMN survey_question_option.survey_question_id IS '소속 문항 ID(FK)';
COMMENT ON COLUMN survey_question_option.display_order IS '선택지 노출 순서';
COMMENT ON COLUMN survey_question_option.option_text IS '선택지 문구';
COMMENT ON COLUMN survey_question_option.created_at IS '생성 시각';
COMMENT ON COLUMN survey_question_option.updated_at IS '수정 시각';

COMMENT ON TABLE survey_submission IS '사용자 설문 제출 헤더';
COMMENT ON COLUMN survey_submission.id IS '제출 PK';
COMMENT ON COLUMN survey_submission.survey_form_id IS '응답한 설문지 ID(FK)';
COMMENT ON COLUMN survey_submission.user_id IS '응답 사용자 ID(FK)';
COMMENT ON COLUMN survey_submission.created_at IS '제출 생성 시각';
COMMENT ON COLUMN survey_submission.updated_at IS '제출 수정 시각';

COMMENT ON TABLE survey_answer IS '제출 내 문항별 응답 본문';
COMMENT ON COLUMN survey_answer.id IS '응답 PK';
COMMENT ON COLUMN survey_answer.survey_submission_id IS '소속 제출 ID(FK)';
COMMENT ON COLUMN survey_answer.survey_question_id IS '응답 대상 문항 ID(FK)';
COMMENT ON COLUMN survey_answer.answer_text IS '주관식 응답 텍스트';
COMMENT ON COLUMN survey_answer.created_at IS '생성 시각';
COMMENT ON COLUMN survey_answer.updated_at IS '수정 시각';

COMMENT ON TABLE survey_answer_option IS '객관식/복수선택 응답의 선택값';
COMMENT ON COLUMN survey_answer_option.id IS '선택 응답 PK';
COMMENT ON COLUMN survey_answer_option.survey_answer_id IS '소속 응답 ID(FK)';
COMMENT ON COLUMN survey_answer_option.display_order IS '선택 순서(복수선택 지원)';
COMMENT ON COLUMN survey_answer_option.option_text IS '선택된 문구 스냅샷';
COMMENT ON COLUMN survey_answer_option.created_at IS '생성 시각';
COMMENT ON COLUMN survey_answer_option.updated_at IS '수정 시각';

-- ----------------------------------------------------------------------------
-- [D] structured survey — 인덱스 (FK 조인·목록 조회)
-- ----------------------------------------------------------------------------

CREATE INDEX IF NOT EXISTS idx_survey_question_form_id
    ON survey_question (survey_form_id);

CREATE INDEX IF NOT EXISTS idx_survey_question_option_question_id
    ON survey_question_option (survey_question_id);

CREATE INDEX IF NOT EXISTS idx_survey_submission_form_id
    ON survey_submission (survey_form_id);

CREATE INDEX IF NOT EXISTS idx_survey_submission_user_id
    ON survey_submission (user_id);

CREATE INDEX IF NOT EXISTS idx_survey_answer_submission_id
    ON survey_answer (survey_submission_id);

CREATE INDEX IF NOT EXISTS idx_survey_answer_question_id
    ON survey_answer (survey_question_id);

CREATE INDEX IF NOT EXISTS idx_survey_answer_option_answer_id
    ON survey_answer_option (survey_answer_id);


--   - 과거 Flyway 이력이 28 이상인 로컬/공유 DB에서도
--   - 현재 리포의 추천 기능 엔티티와 스키마 validate 불일치를 해소한다.
-- ============================================================================

ALTER TABLE products
    ADD COLUMN IF NOT EXISTS is_recommended BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE products
    ADD COLUMN IF NOT EXISTS recommendation_score INT NOT NULL DEFAULT 0;

UPDATE products
SET is_recommended = COALESCE(is_recommended, FALSE);

UPDATE products
SET recommendation_score = COALESCE(recommendation_score, 0);

ALTER TABLE products
    ALTER COLUMN is_recommended SET DEFAULT FALSE;

ALTER TABLE products
    ALTER COLUMN recommendation_score SET DEFAULT 0;

ALTER TABLE products
    ALTER COLUMN is_recommended SET NOT NULL;

ALTER TABLE products
    ALTER COLUMN recommendation_score SET NOT NULL;

COMMENT ON COLUMN products.is_recommended IS '관리자 추천 노출 여부';
COMMENT ON COLUMN products.recommendation_score IS '관리자 수동 추천 점수(높을수록 우선)';
