-- ============================================================================
-- V2 PostgreSQL
-- ----------------------------------------------------------------------------
-- 목적
-- 1) 기존 운영 DB와의 하위 호환을 위해 누락 보정
-- 2) 문항형 설문 도메인 설문 정의/응답 저장 신규 도입
--
-- - 스키마 변경은 생성형으로 구성해 신규/기존 환경 모두 안전
-- - 설문 구조 정규화로 관리자 문항 편집, 사용자 응답 이력, 통계/추천 확장 대응
-- ============================================================================

ALTER TABLE products
    ADD COLUMN IF NOT EXISTS base_price NUMERIC(19, 2) NOT NULL DEFAULT 0;

COMMENT ON COLUMN products.base_price IS '상품 기본가(옵션 합산과 별도)';

-- - 설문 정의의 루트 엔티티
-- - 배포 시점별 설문 버전 전환을 안전하게 운영
CREATE TABLE IF NOT EXISTS survey_form (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(200) NOT NULL,
    description TEXT,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

-- - 문항 텍스트/타입/필수 여부/순서를 저장
CREATE TABLE IF NOT EXISTS survey_question (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    survey_form_id BIGINT NOT NULL,
    display_order INT NOT NULL,
    title VARCHAR(300) NOT NULL,
    description TEXT,
    question_type VARCHAR(30) NOT NULL,
    required BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_survey_question_form FOREIGN KEY (survey_form_id) REFERENCES survey_form(id) ON DELETE CASCADE
);

-- - 객관식 선택지 집합 저장
-- - 문항별 정렬로 UI 순서를 안정적으로 유지
CREATE TABLE IF NOT EXISTS survey_question_option (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    survey_question_id BIGINT NOT NULL,
    display_order INT NOT NULL,
    option_text VARCHAR(300) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_survey_question_option_question FOREIGN KEY (survey_question_id) REFERENCES survey_question(id) ON DELETE CASCADE
);

-- - 사용자 제출 단위 헤더
-- - 통계 집계 기준 키를 명확화
CREATE TABLE IF NOT EXISTS survey_submission (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    survey_form_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_survey_submission_form FOREIGN KEY (survey_form_id) REFERENCES survey_form(id) ON DELETE CASCADE,
    CONSTRAINT fk_survey_submission_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- - 문항별 응답 데이터
-- - 모두 수용하도록 테이블 분리
CREATE TABLE IF NOT EXISTS survey_answer (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    survey_submission_id BIGINT NOT NULL,
    survey_question_id BIGINT NOT NULL,
    answer_text TEXT,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_survey_answer_submission FOREIGN KEY (survey_submission_id) REFERENCES survey_submission(id) ON DELETE CASCADE,
    CONSTRAINT fk_survey_answer_question FOREIGN KEY (survey_question_id) REFERENCES survey_question(id) ON DELETE CASCADE
);

-- - 선택지 응답 스냅샷 저장
-- - 원본 선택지 변경 이후에도 과거 결과 재현 가능
CREATE TABLE IF NOT EXISTS survey_answer_option (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    survey_answer_id BIGINT NOT NULL,
    display_order INT NOT NULL,
    option_text VARCHAR(300) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_survey_answer_option_answer FOREIGN KEY (survey_answer_id) REFERENCES survey_answer(id) ON DELETE CASCADE
);

COMMENT ON TABLE survey_form IS '설문지 메타 정보(제목/설명/활성 상태)';
COMMENT ON COLUMN survey_form.id IS '설문지 PK';
COMMENT ON COLUMN survey_form.title IS '설문지 제목';
COMMENT ON COLUMN survey_form.description IS '설문지 설명';
COMMENT ON COLUMN survey_form.active IS '활성화 여부(true=현재 운영 설문)';
COMMENT ON COLUMN survey_form.created_at IS '생성 시각';
COMMENT ON COLUMN survey_form.updated_at IS '수정 시각';

COMMENT ON TABLE survey_question IS '설문지에 속한 문항 정의';
COMMENT ON COLUMN survey_question.id IS '문항 PK';
COMMENT ON COLUMN survey_question.survey_form_id IS '소속 설문지 ID(FK)';
COMMENT ON COLUMN survey_question.display_order IS '설문 화면 노출 순서';
COMMENT ON COLUMN survey_question.title IS '문항 제목';
COMMENT ON COLUMN survey_question.description IS '문항 부가 설명';
COMMENT ON COLUMN survey_question.question_type IS '문항 타입(TEXT/SINGLE_CHOICE/MULTIPLE_CHOICE)';
COMMENT ON COLUMN survey_question.required IS '필수 응답 여부';
COMMENT ON COLUMN survey_question.created_at IS '생성 시각';
COMMENT ON COLUMN survey_question.updated_at IS '수정 시각';

COMMENT ON TABLE survey_question_option IS '객관식 문항의 선택지 집합';
COMMENT ON COLUMN survey_question_option.id IS '선택지 PK';
COMMENT ON COLUMN survey_question_option.survey_question_id IS '소속 문항 ID(FK)';
COMMENT ON COLUMN survey_question_option.display_order IS '선택지 노출 순서';
COMMENT ON COLUMN survey_question_option.option_text IS '선택지 문구';
COMMENT ON COLUMN survey_question_option.created_at IS '생성 시각';
COMMENT ON COLUMN survey_question_option.updated_at IS '수정 시각';

COMMENT ON TABLE survey_submission IS '사용자 설문 제출 헤더';
COMMENT ON COLUMN survey_submission.id IS '제출 PK';
COMMENT ON COLUMN survey_submission.survey_form_id IS '응답한 설문지 ID(FK)';
COMMENT ON COLUMN survey_submission.user_id IS '응답 사용자 ID(FK)';
COMMENT ON COLUMN survey_submission.created_at IS '제출 생성 시각';
COMMENT ON COLUMN survey_submission.updated_at IS '제출 수정 시각';

COMMENT ON TABLE survey_answer IS '제출 내 문항별 응답 본문';
COMMENT ON COLUMN survey_answer.id IS '응답 PK';
COMMENT ON COLUMN survey_answer.survey_submission_id IS '소속 제출 ID(FK)';
COMMENT ON COLUMN survey_answer.survey_question_id IS '응답 대상 문항 ID(FK)';
COMMENT ON COLUMN survey_answer.answer_text IS '주관식 응답 텍스트';
COMMENT ON COLUMN survey_answer.created_at IS '생성 시각';
COMMENT ON COLUMN survey_answer.updated_at IS '수정 시각';

COMMENT ON TABLE survey_answer_option IS '객관식/복수선택 응답의 선택값';
COMMENT ON COLUMN survey_answer_option.id IS '선택 응답 PK';
COMMENT ON COLUMN survey_answer_option.survey_answer_id IS '소속 응답 ID(FK)';
COMMENT ON COLUMN survey_answer_option.display_order IS '선택 순서(복수선택 지원)';
COMMENT ON COLUMN survey_answer_option.option_text IS '선택된 문구 스냅샷';
COMMENT ON COLUMN survey_answer_option.created_at IS '생성 시각';
COMMENT ON COLUMN survey_answer_option.updated_at IS '수정 시각';

CREATE INDEX IF NOT EXISTS idx_survey_question_form_id ON survey_question(survey_form_id);
CREATE INDEX IF NOT EXISTS idx_survey_question_option_question_id ON survey_question_option(survey_question_id);
CREATE INDEX IF NOT EXISTS idx_survey_submission_form_id ON survey_submission(survey_form_id);
CREATE INDEX IF NOT EXISTS idx_survey_submission_user_id ON survey_submission(user_id);
CREATE INDEX IF NOT EXISTS idx_survey_answer_submission_id ON survey_answer(survey_submission_id);
CREATE INDEX IF NOT EXISTS idx_survey_answer_question_id ON survey_answer(survey_question_id);
CREATE INDEX IF NOT EXISTS idx_survey_answer_option_answer_id ON survey_answer_option(survey_answer_id);
