-- =============================================================================
-- V2: 예약 홀드/결제/알림/권한 제약 확장
-- =============================================================================

-- -----------------------------------------------------------------------------
-- users: 역할 제약 확장(USER -> USER, ADMIN)
-- -----------------------------------------------------------------------------
ALTER TABLE users DROP CONSTRAINT chk_users_role;
ALTER TABLE users ADD CONSTRAINT chk_users_role CHECK (role IN ('USER', 'ADMIN'));

COMMENT ON COLUMN users.role IS '권한 역할(USER, ADMIN)';

-- -----------------------------------------------------------------------------
-- reservation_slots: 홀드 상태 컬럼 추가
-- -----------------------------------------------------------------------------
ALTER TABLE reservation_slots ADD COLUMN hold_reservation_id BIGINT;
ALTER TABLE reservation_slots ADD COLUMN hold_expires_at TIMESTAMP;
ALTER TABLE reservation_slots
    ADD CONSTRAINT fk_reservation_slots_hold_reservation FOREIGN KEY (hold_reservation_id) REFERENCES reservations (id);

CREATE INDEX idx_reservation_slots_hold ON reservation_slots (hold_reservation_id, hold_expires_at);

COMMENT ON COLUMN reservation_slots.hold_reservation_id IS '현재 슬롯을 홀드 중인 reservations.id';
COMMENT ON COLUMN reservation_slots.hold_expires_at IS '홀드 만료 시각(만료 시 재사용 가능)';

-- -----------------------------------------------------------------------------
-- reservations: 만료/확정/취소 메타 추가
-- -----------------------------------------------------------------------------
ALTER TABLE reservations ADD COLUMN expires_at TIMESTAMP;
ALTER TABLE reservations ADD COLUMN confirmed_at TIMESTAMP;
ALTER TABLE reservations ADD COLUMN canceled_at TIMESTAMP;
ALTER TABLE reservations ADD COLUMN cancel_reason VARCHAR(40);
ALTER TABLE reservations
    ADD CONSTRAINT chk_reservations_cancel_reason CHECK (
        cancel_reason IS NULL OR cancel_reason IN ('USER_REQUESTED', 'PAYMENT_FAILED', 'PAYMENT_EXPIRED', 'ADMIN_CANCELED')
    );

CREATE INDEX idx_reservations_status_expires_at ON reservations (status, expires_at);

COMMENT ON COLUMN reservations.expires_at IS '예약 만료 시각(PENDING 타임아웃 등)';
COMMENT ON COLUMN reservations.confirmed_at IS '예약 확정 시각';
COMMENT ON COLUMN reservations.canceled_at IS '예약 취소 시각';
COMMENT ON COLUMN reservations.cancel_reason IS '취소 사유(USER_REQUESTED, PAYMENT_FAILED, PAYMENT_EXPIRED, ADMIN_CANCELED)';

-- -----------------------------------------------------------------------------
-- payments: 예약 결제 상태 추적
-- -----------------------------------------------------------------------------
CREATE TABLE payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reservation_id BIGINT NOT NULL,
    provider VARCHAR(20) NOT NULL,
    payment_reference VARCHAR(80) NOT NULL,
    amount NUMERIC(15, 2) NOT NULL,
    status VARCHAR(20) NOT NULL,
    approved_at TIMESTAMP,
    failed_at TIMESTAMP,
    expired_at TIMESTAMP,
    failure_reason VARCHAR(255),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_payments_reservation_id UNIQUE (reservation_id),
    CONSTRAINT uk_payments_reference UNIQUE (payment_reference),
    CONSTRAINT fk_payments_reservation FOREIGN KEY (reservation_id) REFERENCES reservations (id),
    CONSTRAINT chk_payments_provider CHECK (provider IN ('MOCK')),
    CONSTRAINT chk_payments_status CHECK (status IN ('PENDING', 'SUCCEEDED', 'FAILED', 'CANCELED', 'EXPIRED'))
);

CREATE INDEX idx_payments_status_updated_at ON payments (status, updated_at);

COMMENT ON TABLE payments IS '예약별 결제 정보 및 상태 이력 타임스탬프';
COMMENT ON COLUMN payments.id IS '결제 PK';
COMMENT ON COLUMN payments.reservation_id IS 'reservations.id FK(예약당 1건)';
COMMENT ON COLUMN payments.provider IS '결제 제공자(현재 MOCK)';
COMMENT ON COLUMN payments.payment_reference IS '외부 결제 레퍼런스(유니크)';
COMMENT ON COLUMN payments.amount IS '결제 금액';
COMMENT ON COLUMN payments.status IS '결제 상태(PENDING/SUCCEEDED/FAILED/CANCELED/EXPIRED)';
COMMENT ON COLUMN payments.approved_at IS '승인 시각';
COMMENT ON COLUMN payments.failed_at IS '실패 시각';
COMMENT ON COLUMN payments.expired_at IS '만료 시각';
COMMENT ON COLUMN payments.failure_reason IS '실패 사유 메시지';
COMMENT ON COLUMN payments.created_at IS '생성 시각';
COMMENT ON COLUMN payments.updated_at IS '수정 시각';

-- -----------------------------------------------------------------------------
-- notifications: 사용자 알림
-- -----------------------------------------------------------------------------
CREATE TABLE notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    type VARCHAR(40) NOT NULL,
    title VARCHAR(120) NOT NULL,
    message VARCHAR(500) NOT NULL,
    link VARCHAR(255),
    read_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_notifications_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT chk_notifications_type CHECK (type IN ('RESERVATION_CONFIRMED', 'RESERVATION_CANCELED', 'PAYMENT_FAILED', 'PAYMENT_EXPIRED'))
);

CREATE INDEX idx_notifications_user_read_created ON notifications (user_id, read_at, created_at);

COMMENT ON TABLE notifications IS '사용자 대상 시스템 알림';
COMMENT ON COLUMN notifications.id IS '알림 PK';
COMMENT ON COLUMN notifications.user_id IS '수신자 users.id';
COMMENT ON COLUMN notifications.type IS '알림 타입(예약/결제 이벤트)';
COMMENT ON COLUMN notifications.title IS '알림 제목';
COMMENT ON COLUMN notifications.message IS '알림 본문';
COMMENT ON COLUMN notifications.link IS '클릭 이동 링크(옵션)';
COMMENT ON COLUMN notifications.read_at IS '읽음 처리 시각(NULL이면 미읽음)';
COMMENT ON COLUMN notifications.created_at IS '생성 시각';
COMMENT ON COLUMN notifications.updated_at IS '수정 시각';
