-- =============================================================================
-- V3: images 테이블 누락 보정
-- 기존 환경에서 V1 이력은 있으나 images 테이블이 없는 경우를 복구한다.
-- 컬럼 의미 파악을 돕기 위해 테이블/컬럼 주석과 더미 데이터(1건)를 함께 추가한다.
-- =============================================================================

CREATE TABLE IF NOT EXISTS images (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aggregate_type VARCHAR(30) NOT NULL,
    aggregate_id BIGINT NOT NULL,
    original_filename VARCHAR(255) NOT NULL,
    unique_filename VARCHAR(255) NOT NULL,
    extension VARCHAR(20) NOT NULL,
    file_size BIGINT NOT NULL,
    url VARCHAR(500) NOT NULL,
    sort_order INT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT chk_images_aggregate_type CHECK (aggregate_type IN ('PRODUCT', 'OPTION', 'USER', 'PRODUCT_REVIEW')),
    CONSTRAINT chk_images_sort_order CHECK (sort_order >= 0),
    CONSTRAINT chk_images_file_size CHECK (file_size > 0)
);

CREATE INDEX IF NOT EXISTS idx_images_aggregate ON images (aggregate_type, aggregate_id, sort_order);

-- -----------------------------------------------------------------------------
-- 컬럼 설명 주석
-- -----------------------------------------------------------------------------
COMMENT ON TABLE images IS '도메인 엔티티별 저장 이미지 메타';
COMMENT ON COLUMN images.id IS '이미지 PK(자동 증가)';
COMMENT ON COLUMN images.aggregate_type IS '이미지가 속한 도메인 타입(PRODUCT/OPTION/USER/PRODUCT_REVIEW)';
COMMENT ON COLUMN images.aggregate_id IS 'aggregate_type에 해당하는 실제 엔티티 PK';
COMMENT ON COLUMN images.original_filename IS '사용자가 업로드한 원본 파일명';
COMMENT ON COLUMN images.unique_filename IS '스토리지 저장용 유니크 파일명';
COMMENT ON COLUMN images.extension IS '파일 확장자(예: jpg, png)';
COMMENT ON COLUMN images.file_size IS '파일 크기(byte)';
COMMENT ON COLUMN images.url IS '클라이언트가 접근 가능한 이미지 URL';
COMMENT ON COLUMN images.sort_order IS '동일 엔티티 내 이미지 정렬 순서(0부터)';
COMMENT ON COLUMN images.created_at IS '생성 시각';
COMMENT ON COLUMN images.updated_at IS '수정 시각';

-- -----------------------------------------------------------------------------
-- 더미 데이터(개발 확인용)
-- images 테이블이 비어있을 때만 1건 삽입한다.
-- -----------------------------------------------------------------------------
INSERT INTO images (
    aggregate_type,
    aggregate_id,
    original_filename,
    unique_filename,
    extension,
    file_size,
    url,
    sort_order,
    created_at,
    updated_at
)
SELECT
    'PRODUCT',
    1,
    'sample-product-image.jpg',
    'sample-product-image-0001.jpg',
    'jpg',
    1024,
    'https://mock-cloud.example/images/sample-product-image-0001.jpg',
    0,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
WHERE NOT EXISTS (SELECT 1 FROM images);
