-- Newsletter admin domain tables
-- 뉴스레터 본문은 문단 단위로 정규화하여 목록/상세/관리 화면에서 재사용한다.

-- 뉴스레터 마스터
create table if not exists newsletters (
    id bigint generated by default as identity primary key,
    slug varchar(160) not null,
    title varchar(200) not null,
    category_label varchar(80) not null,
    published_at date not null,
    image_url varchar(500) not null,
    summary text not null,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,
    constraint uk_newsletter_slug unique (slug)
);

-- 뉴스레터 태그
create table if not exists newsletter_tags (
    id bigint generated by default as identity primary key,
    newsletter_id bigint not null references newsletters(id) on delete cascade,
    display_order integer not null,
    tag_name varchar(80) not null,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,
    constraint uk_newsletter_tag_name unique (newsletter_id, tag_name)
);

-- 뉴스레터 문단
create table if not exists newsletter_paragraphs (
    id bigint generated by default as identity primary key,
    newsletter_id bigint not null references newsletters(id) on delete cascade,
    display_order integer not null,
    body text not null,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,
    constraint uk_newsletter_paragraph_order unique (newsletter_id, display_order)
);

-- 발행일 최신순 조회 인덱스
create index if not exists idx_newsletters_published_at on newsletters(published_at);
