-- =============================================================================
-- Flyway V16 - 구독자 및 콘텐츠 발송 이력 테이블
-- =============================================================================
-- 이메일 구독 상태(동의/활성 여부)와 뉴스레터·웹진 발송 결과를 추적한다.
-- 동일 콘텐츠의 채널별 중복 발송 이력은 UNIQUE 제약으로 방지한다.
-- =============================================================================

create table if not exists email_subscriptions (
    id bigint generated by default as identity primary key,
    email varchar(255) not null, -- 구독자 이메일(유일)
    subscribed_newsletters boolean not null default true,
    subscribed_issues boolean not null default true,
    consented_at timestamp not null,
    subscribed_at timestamp not null,
    subscription_source varchar(50) not null, -- 구독 유입 채널
    active boolean not null default true,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,
    constraint uk_email_subscriptions_email unique (email)
);

create table if not exists subscription_dispatch_histories (
    id bigint generated by default as identity primary key,
    content_type varchar(40) not null,
    content_slug varchar(160) not null,
    content_title varchar(255) not null,
    content_summary varchar(1000),
    dispatch_channel varchar(20) not null,
    dispatch_status varchar(20) not null, -- 발송 상태(예: SENT, FAILED)
    recipient_count bigint not null,
    content_created_at timestamp,
    dispatched_at timestamp not null,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,
    constraint uk_subscription_dispatch_content unique (content_type, content_slug, dispatch_channel)
);

comment on table email_subscriptions is '구독자 마스터 테이블(수신 동의/활성 상태 포함)';
comment on column email_subscriptions.email is '구독자 이메일(전역 유일)';
comment on column email_subscriptions.subscribed_newsletters is '뉴스레터 수신 여부';
comment on column email_subscriptions.subscribed_issues is '웹진/이슈 수신 여부';
comment on column email_subscriptions.consented_at is '수신 동의 시각';
comment on column email_subscriptions.subscribed_at is '구독 등록 시각';
comment on column email_subscriptions.subscription_source is '구독 유입 채널';
comment on column email_subscriptions.active is '활성 구독 상태';
comment on column email_subscriptions.created_at is '생성 시각';
comment on column email_subscriptions.updated_at is '마지막 수정 시각';

comment on table subscription_dispatch_histories is '콘텐츠 발송 이력 테이블';
comment on column subscription_dispatch_histories.content_type is '콘텐츠 유형(예: NEWSLETTER, WEBZINE)';
comment on column subscription_dispatch_histories.content_slug is '콘텐츠 고유 slug/키';
comment on column subscription_dispatch_histories.content_title is '발송 당시 제목 스냅샷';
comment on column subscription_dispatch_histories.content_summary is '발송 당시 요약 스냅샷';
comment on column subscription_dispatch_histories.dispatch_channel is '발송 채널(예: EMAIL)';
comment on column subscription_dispatch_histories.dispatch_status is '발송 상태(예: SENT, FAILED)';
comment on column subscription_dispatch_histories.recipient_count is '발송 대상자 수';
comment on column subscription_dispatch_histories.content_created_at is '콘텐츠 원본 생성 시각';
comment on column subscription_dispatch_histories.dispatched_at is '실제 발송 시각';
comment on column subscription_dispatch_histories.created_at is '생성 시각';
comment on column subscription_dispatch_histories.updated_at is '마지막 수정 시각';

create index if not exists idx_email_subscriptions_active on email_subscriptions(active);
create index if not exists idx_subscription_dispatch_histories_dispatched_at on subscription_dispatch_histories(dispatched_at);

