-- =============================================================================
-- V19: 플랫폼 인증용 users 확장·비밀번호 이력·역할(USER, ADMIN)
-- =============================================================================

ALTER TABLE users DROP CONSTRAINT chk_users_role;
ALTER TABLE users ADD CONSTRAINT chk_users_role CHECK (role IN ('USER', 'ADMIN'));

COMMENT ON COLUMN users.role IS '권한 역할(USER: 일반, ADMIN: 관리자)';

ALTER TABLE users ADD COLUMN IF NOT EXISTS account_status VARCHAR(20) NOT NULL DEFAULT 'APPROVED';
ALTER TABLE users ADD COLUMN IF NOT EXISTS platform_username VARCHAR(50) NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS login_fail_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS account_locked_at TIMESTAMP NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS password_changed_at TIMESTAMP NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS last_password_change_date DATE NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS password_change_daily_count INTEGER NOT NULL DEFAULT 0;

CREATE UNIQUE INDEX IF NOT EXISTS uq_users_platform_username ON users (platform_username);

COMMENT ON COLUMN users.account_status IS '계정 승인·정지 상태(PENDING, APPROVED, REJECTED, SUSPENDED, WITHDRAWN)';
COMMENT ON COLUMN users.platform_username IS '플랫폼 가입 시 로그인명(계정 복구 시 이메일과 함께 사용)';
COMMENT ON COLUMN users.login_fail_count IS '연속 로그인 실패 횟수';
COMMENT ON COLUMN users.account_locked_at IS '계정 잠금 처리 시각';
COMMENT ON COLUMN users.password_changed_at IS '마지막 비밀번호 변경 시각';
COMMENT ON COLUMN users.last_password_change_date IS '당일 비밀번호 변경 횟수 집계 기준일';
COMMENT ON COLUMN users.password_change_daily_count IS '기준일 당일 비밀번호 변경 횟수';

CREATE TABLE IF NOT EXISTS user_password_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    password_hash VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_user_password_history_user_created
    ON user_password_history (user_id, created_at DESC);

COMMENT ON TABLE user_password_history IS '과거 비밀번호 해시(재사용 방지 조회용)';
COMMENT ON COLUMN user_password_history.id IS '이력 행 PK';
COMMENT ON COLUMN user_password_history.user_id IS 'users.id FK';
COMMENT ON COLUMN user_password_history.password_hash IS 'BCrypt 등으로 인코딩된 비밀번호';
COMMENT ON COLUMN user_password_history.created_at IS '이력 저장 시각';
