-- 공통 전체 스키마
-- 새 데이터베이스를 처음 만들 때만 사용한다. 이미 같은 스키마가 반영된 환경에는 실행하지 않는다.

-- 초기 스키마

---
-- users: 애플리케이션 회원
---
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL,
    nickname VARCHAR(10) NOT NULL,
    role VARCHAR(255) NOT NULL,
    last_login_at TIMESTAMP,
    CONSTRAINT chk_users_role CHECK (role IN ('USER'))
);

CREATE INDEX idx_users_email ON users (email);

COMMENT ON TABLE users IS '서비스 회원. OAuth 연동은 user_oauths 참조';
COMMENT ON COLUMN users.id IS '회원 PK';
COMMENT ON COLUMN users.email IS '로그인·식별용 이메일(유니크 인덱스)';
COMMENT ON COLUMN users.nickname IS '표시 닉네임';
COMMENT ON COLUMN users.role IS '권한 역할(현재 USER만 허용)';
COMMENT ON COLUMN users.last_login_at IS '마지막 로그인 시각';

---
-- user_oauths: OAuth 제공자별 계정 연결
---
CREATE TABLE user_oauths (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    provider VARCHAR(255) NOT NULL,
    provider_id VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    CONSTRAINT chk_user_oauths_provider CHECK (provider IN ('GOOGLE', 'TEST'))
);

CREATE INDEX idx_user_oauths_user_id ON user_oauths (user_id);
CREATE INDEX idx_user_oauths_provider_provider_id ON user_oauths (provider, provider_id);
CREATE INDEX idx_user_oauths_email ON user_oauths (email);

COMMENT ON TABLE user_oauths IS '외부 OAuth 계정과 users 매핑';
COMMENT ON COLUMN user_oauths.id IS '연동 행 PK';
COMMENT ON COLUMN user_oauths.user_id IS 'users.id FK';
COMMENT ON COLUMN user_oauths.provider IS 'OAuth 제공자(GOOGLE, TEST)';
COMMENT ON COLUMN user_oauths.provider_id IS '제공자 측 사용자 식별자';
COMMENT ON COLUMN user_oauths.email IS '제공자가 넘긴 이메일';

---
-- options: 상품에 붙는 옵션
---
CREATE TABLE options (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    description TEXT NOT NULL,
    price NUMERIC(38, 2) NOT NULL,
    location VARCHAR(200) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

COMMENT ON TABLE options IS '상품 옵션 마스터(가격·설명·위치 문구)';
COMMENT ON COLUMN options.id IS '옵션 PK';
COMMENT ON COLUMN options.name IS '옵션명';
COMMENT ON COLUMN options.description IS '옵션 상세 설명';
COMMENT ON COLUMN options.price IS '옵션 가격';
COMMENT ON COLUMN options.location IS '옵션 관련 위치 표시 문자열';
COMMENT ON COLUMN options.created_at IS '생성 시각';
COMMENT ON COLUMN options.updated_at IS '수정 시각';

---
-- products: 상품 마스터
---
CREATE TABLE products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    description TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

COMMENT ON TABLE products IS '상품 기본 정보';
COMMENT ON COLUMN products.id IS '상품 PK';
COMMENT ON COLUMN products.name IS '상품명';
COMMENT ON COLUMN products.description IS '상품 설명';
COMMENT ON COLUMN products.created_at IS '생성 시각';
COMMENT ON COLUMN products.updated_at IS '수정 시각';

---
-- product_option: 상품-옵션 N:M
---
CREATE TABLE product_option (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL,
    option_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_product_option UNIQUE (product_id, option_id),
    CONSTRAINT fk_product_option_product FOREIGN KEY (product_id) REFERENCES products (id),
    CONSTRAINT fk_product_option_option FOREIGN KEY (option_id) REFERENCES options (id)
);

CREATE INDEX idx_product_option_product_id ON product_option (product_id);
CREATE INDEX idx_product_option_option_id ON product_option (option_id);

COMMENT ON TABLE product_option IS '상품에 포함된 옵션 연결';
COMMENT ON COLUMN product_option.id IS '연결 행 PK';
COMMENT ON COLUMN product_option.product_id IS 'products.id FK';
COMMENT ON COLUMN product_option.option_id IS 'options.id FK';
COMMENT ON COLUMN product_option.created_at IS '생성 시각';
COMMENT ON COLUMN product_option.updated_at IS '수정 시각';

---
-- product_tag: 상품 태그
---
CREATE TABLE product_tag (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL,
    tag_name VARCHAR(50) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_product_tag UNIQUE (product_id, tag_name),
    CONSTRAINT fk_product_tag_product FOREIGN KEY (product_id) REFERENCES products (id)
);

CREATE INDEX idx_product_tag_tag_name ON product_tag (tag_name);
CREATE INDEX idx_product_tag_product_id ON product_tag (product_id);

COMMENT ON TABLE product_tag IS '상품별 검색·분류용 태그';
COMMENT ON COLUMN product_tag.id IS '태그 행 PK';
COMMENT ON COLUMN product_tag.product_id IS 'products.id FK';
COMMENT ON COLUMN product_tag.tag_name IS '태그 문자열';
COMMENT ON COLUMN product_tag.created_at IS '생성 시각';
COMMENT ON COLUMN product_tag.updated_at IS '수정 시각';

---
-- product_locations: 상품 대표 위치
---
CREATE TABLE product_locations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL,
    name VARCHAR(120) NOT NULL,
    latitude NUMERIC(10, 7) NOT NULL,
    longitude NUMERIC(10, 7) NOT NULL,
    road_address_name VARCHAR(255),
    address_name VARCHAR(255),
    kakao_place_id VARCHAR(40) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_product_locations_product UNIQUE (product_id),
    CONSTRAINT fk_product_locations_product FOREIGN KEY (product_id) REFERENCES products (id)
);

COMMENT ON TABLE product_locations IS '상품당 하나의 지도/주소 정보';
COMMENT ON COLUMN product_locations.id IS '위치 행 PK';
COMMENT ON COLUMN product_locations.product_id IS 'products.id FK';
COMMENT ON COLUMN product_locations.name IS '장소 표시명';
COMMENT ON COLUMN product_locations.latitude IS '위도';
COMMENT ON COLUMN product_locations.longitude IS '경도';
COMMENT ON COLUMN product_locations.road_address_name IS '도로명 주소';
COMMENT ON COLUMN product_locations.address_name IS '지번/일반 주소';
COMMENT ON COLUMN product_locations.kakao_place_id IS '카카오 장소 ID';
COMMENT ON COLUMN product_locations.created_at IS '생성 시각';
COMMENT ON COLUMN product_locations.updated_at IS '수정 시각';

---
-- reservation_slots: 상품별 예약 가능 슬롯
---
CREATE TABLE reservation_slots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL,
    reservation_date DATE NOT NULL,
    start_time TIME NOT NULL,
    end_time TIME NOT NULL,
    is_booked BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_reservation_slot_product_date_start UNIQUE (product_id, reservation_date, start_time),
    CONSTRAINT fk_reservation_slots_product FOREIGN KEY (product_id) REFERENCES products (id),
    CONSTRAINT chk_reservation_slots_time CHECK (end_time > start_time)
);

CREATE INDEX idx_reservation_slots_product_id ON reservation_slots (product_id);

COMMENT ON TABLE reservation_slots IS '예약 가능 시간 슬롯';
COMMENT ON COLUMN reservation_slots.id IS '슬롯 PK';
COMMENT ON COLUMN reservation_slots.product_id IS 'products.id FK';
COMMENT ON COLUMN reservation_slots.reservation_date IS '슬롯 날짜';
COMMENT ON COLUMN reservation_slots.start_time IS '시작 시각';
COMMENT ON COLUMN reservation_slots.end_time IS '종료 시각(시작보다 커야 함)';
COMMENT ON COLUMN reservation_slots.is_booked IS '예약 확정 등으로 점유 여부';
COMMENT ON COLUMN reservation_slots.created_at IS '생성 시각';
COMMENT ON COLUMN reservation_slots.updated_at IS '수정 시각';

---
-- reservations: 사용자 예약
---
CREATE TABLE reservations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reservation_slot_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    visit_date DATE NOT NULL,
    visit_start_time TIME NOT NULL,
    visit_end_time TIME NOT NULL,
    total_price NUMERIC(15, 2) NOT NULL,
    status VARCHAR(20) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_reservations_reservation_slot FOREIGN KEY (reservation_slot_id) REFERENCES reservation_slots (id),
    CONSTRAINT chk_reservations_status CHECK (status IN ('PREBOOK', 'PENDING', 'BOOKED', 'COMPLETED', 'CANCELED'))
);

CREATE INDEX idx_reservations_user_visit_time ON reservations (user_id, visit_date, visit_start_time);
CREATE INDEX idx_reservations_reservation_slot_id ON reservations (reservation_slot_id);

COMMENT ON TABLE reservations IS '회원의 예약 건';
COMMENT ON COLUMN reservations.id IS '예약 PK';
COMMENT ON COLUMN reservations.reservation_slot_id IS 'reservation_slots.id FK';
COMMENT ON COLUMN reservations.user_id IS '예약자 users.id';
COMMENT ON COLUMN reservations.visit_date IS '방문일';
COMMENT ON COLUMN reservations.visit_start_time IS '방문 시작 시각';
COMMENT ON COLUMN reservations.visit_end_time IS '방문 종료 시각';
COMMENT ON COLUMN reservations.total_price IS '예약 총액';
COMMENT ON COLUMN reservations.status IS '예약 상태(PREBOOK/PENDING/BOOKED/COMPLETED/CANCELED)';
COMMENT ON COLUMN reservations.created_at IS '생성 시각';
COMMENT ON COLUMN reservations.updated_at IS '수정 시각';

---
-- product_reviews: 상품 리뷰
---
CREATE TABLE product_reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    rating INT NOT NULL,
    content VARCHAR(2000) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_product_review_user UNIQUE (product_id, user_id),
    CONSTRAINT fk_product_reviews_product FOREIGN KEY (product_id) REFERENCES products (id),
    CONSTRAINT chk_product_reviews_rating CHECK (rating BETWEEN 1 AND 5)
);

CREATE INDEX idx_product_reviews_product_id ON product_reviews (product_id);
CREATE INDEX idx_product_reviews_user_id ON product_reviews (user_id);

COMMENT ON TABLE product_reviews IS '상품별 사용자 리뷰(상품·사용자 유니크)';
COMMENT ON COLUMN product_reviews.id IS '리뷰 PK';
COMMENT ON COLUMN product_reviews.product_id IS 'products.id FK';
COMMENT ON COLUMN product_reviews.user_id IS '작성자 users.id';
COMMENT ON COLUMN product_reviews.rating IS '별점 1~5';
COMMENT ON COLUMN product_reviews.content IS '리뷰 본문';
COMMENT ON COLUMN product_reviews.created_at IS '생성 시각';
COMMENT ON COLUMN product_reviews.updated_at IS '수정 시각';

---
-- images: 집계 타입별 첨부 이미지
---
CREATE TABLE images (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aggregate_type VARCHAR(30) NOT NULL,
    aggregate_id BIGINT NOT NULL,
    original_filename VARCHAR(255) NOT NULL,
    unique_filename VARCHAR(255) NOT NULL,
    extension VARCHAR(20) NOT NULL,
    file_size BIGINT NOT NULL,
    url VARCHAR(500) NOT NULL,
    sort_order INT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT chk_images_aggregate_type CHECK (aggregate_type IN ('PRODUCT', 'OPTION', 'USER', 'PRODUCT_REVIEW')),
    CONSTRAINT chk_images_sort_order CHECK (sort_order >= 0),
    CONSTRAINT chk_images_file_size CHECK (file_size > 0)
);

CREATE INDEX idx_images_aggregate ON images (aggregate_type, aggregate_id, sort_order);

COMMENT ON TABLE images IS '도메인 엔티티별 저장 이미지 메타';
COMMENT ON COLUMN images.id IS '이미지 PK';
COMMENT ON COLUMN images.aggregate_type IS '소속 엔티티 종류';
COMMENT ON COLUMN images.aggregate_id IS '소속 엔티티 PK';
COMMENT ON COLUMN images.original_filename IS '업로드 원본 파일명';
COMMENT ON COLUMN images.unique_filename IS '저장용 유니크 파일명';
COMMENT ON COLUMN images.extension IS '확장자';
COMMENT ON COLUMN images.file_size IS '파일 크기(바이트, 양수)';
COMMENT ON COLUMN images.url IS '접근 URL';
COMMENT ON COLUMN images.sort_order IS '같은 aggregate 내 정렬 순서(0 이상)';
COMMENT ON COLUMN images.created_at IS '생성 시각';
COMMENT ON COLUMN images.updated_at IS '수정 시각';

---
-- user_survey: 온보딩/취향 설문
---
CREATE TABLE user_survey (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    concept VARCHAR(30) NOT NULL,
    idol_name VARCHAR(255) NOT NULL,
    visit_start_date DATE NOT NULL,
    visit_end_date DATE NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_user_survey_user_id UNIQUE (user_id),
    CONSTRAINT fk_user_survey_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT chk_user_survey_concept CHECK (concept IN ('GIRL_CRUSH', 'LOVELY_FRESH', 'ELEGANT_GLAM', 'DREAMY', 'HIGHTEEN', 'ETC')),
    CONSTRAINT chk_user_survey_visit_dates CHECK (visit_end_date >= visit_start_date)
);

CREATE INDEX idx_user_survey_user_id ON user_survey (user_id);

COMMENT ON TABLE user_survey IS '사용자 설문(콘셉트·아이돌명·방문 기간)';
COMMENT ON COLUMN user_survey.id IS '설문 PK';
COMMENT ON COLUMN user_survey.user_id IS 'users.id FK';
COMMENT ON COLUMN user_survey.concept IS '선호 콘셉트 코드';
COMMENT ON COLUMN user_survey.idol_name IS '관심 아이돌/그룹명';
COMMENT ON COLUMN user_survey.visit_start_date IS '방문 희망 시작일';
COMMENT ON COLUMN user_survey.visit_end_date IS '방문 희망 종료일';
COMMENT ON COLUMN user_survey.created_at IS '생성 시각';
COMMENT ON COLUMN user_survey.updated_at IS '수정 시각';

---
-- user_survey_places: 설문에 선택한 장소 목록
---
CREATE TABLE user_survey_places (
    user_survey_id BIGINT NOT NULL,
    place VARCHAR(100) NOT NULL,
    CONSTRAINT fk_user_survey_places_survey FOREIGN KEY (user_survey_id) REFERENCES user_survey (id)
);

CREATE INDEX idx_user_survey_places_survey_id ON user_survey_places (user_survey_id);

COMMENT ON TABLE user_survey_places IS '설문에 기입한 방문 희망 장소(복수 행)';
COMMENT ON COLUMN user_survey_places.user_survey_id IS 'user_survey.id FK';
COMMENT ON COLUMN user_survey_places.place IS '장소명';

---
-- wishes: 상품 찜
---
CREATE TABLE wishes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_user_product_wish UNIQUE (user_id, product_id),
    CONSTRAINT fk_wishes_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_wishes_product FOREIGN KEY (product_id) REFERENCES products (id)
);

CREATE INDEX idx_wishes_user_id ON wishes (user_id);
CREATE INDEX idx_wishes_product_id ON wishes (product_id);

COMMENT ON TABLE wishes IS '사용자의 상품 찜';
COMMENT ON COLUMN wishes.id IS '찜 PK';
COMMENT ON COLUMN wishes.user_id IS 'users.id FK';
COMMENT ON COLUMN wishes.product_id IS 'products.id FK';
COMMENT ON COLUMN wishes.created_at IS '생성 시각';
COMMENT ON COLUMN wishes.updated_at IS '수정 시각';

---
-- schedules: 마이페이지 일정
---
CREATE TABLE schedules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    title VARCHAR(100) NOT NULL,
    start_at TIMESTAMP NOT NULL,
    end_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT chk_schedules_time CHECK (end_at >= start_at)
);

CREATE INDEX idx_schedule_user_start ON schedules (user_id, start_at);

COMMENT ON TABLE schedules IS '사용자 일정(상품 참조)';
COMMENT ON COLUMN schedules.id IS '일정 PK';
COMMENT ON COLUMN schedules.user_id IS 'users.id';
COMMENT ON COLUMN schedules.product_id IS 'products.id';
COMMENT ON COLUMN schedules.title IS '일정 제목';
COMMENT ON COLUMN schedules.start_at IS '시작 시각';
COMMENT ON COLUMN schedules.end_at IS '종료 시각(시작 이상)';
COMMENT ON COLUMN schedules.created_at IS '생성 시각';
COMMENT ON COLUMN schedules.updated_at IS '수정 시각';

-- 예약 보류, 결제, 알림, 회원 권한 관련 변경

---
-- users: 허용되는 role 값 범위를 넓힌다
---
ALTER TABLE users DROP CONSTRAINT chk_users_role;
ALTER TABLE users ADD CONSTRAINT chk_users_role CHECK (role IN ('USER', 'ADMIN'));

COMMENT ON COLUMN users.role IS '권한 역할(USER, ADMIN)';

---
-- reservation_slots: 홀드 상태 컬럼 추가
---
ALTER TABLE reservation_slots ADD COLUMN hold_reservation_id BIGINT;
ALTER TABLE reservation_slots ADD COLUMN hold_expires_at TIMESTAMP;
ALTER TABLE reservation_slots
    ADD CONSTRAINT fk_reservation_slots_hold_reservation FOREIGN KEY (hold_reservation_id) REFERENCES reservations (id);

CREATE INDEX idx_reservation_slots_hold ON reservation_slots (hold_reservation_id, hold_expires_at);

COMMENT ON COLUMN reservation_slots.hold_reservation_id IS '현재 슬롯을 홀드 중인 reservations.id';
COMMENT ON COLUMN reservation_slots.hold_expires_at IS '홀드 만료 시각(만료 시 재사용 가능)';

---
-- reservations: 만료/확정/취소 메타 추가
---
ALTER TABLE reservations ADD COLUMN expires_at TIMESTAMP;
ALTER TABLE reservations ADD COLUMN confirmed_at TIMESTAMP;
ALTER TABLE reservations ADD COLUMN canceled_at TIMESTAMP;
ALTER TABLE reservations ADD COLUMN cancel_reason VARCHAR(40);
ALTER TABLE reservations
    ADD CONSTRAINT chk_reservations_cancel_reason CHECK (
        cancel_reason IS NULL OR cancel_reason IN ('USER_REQUESTED', 'PAYMENT_FAILED', 'PAYMENT_EXPIRED', 'ADMIN_CANCELED')
    );

CREATE INDEX idx_reservations_status_expires_at ON reservations (status, expires_at);

COMMENT ON COLUMN reservations.expires_at IS '예약 만료 시각(PENDING 타임아웃 등)';
COMMENT ON COLUMN reservations.confirmed_at IS '예약 확정 시각';
COMMENT ON COLUMN reservations.canceled_at IS '예약 취소 시각';
COMMENT ON COLUMN reservations.cancel_reason IS '취소 사유(USER_REQUESTED, PAYMENT_FAILED, PAYMENT_EXPIRED, ADMIN_CANCELED)';

---
-- payments: 예약 결제 상태 추적
---
CREATE TABLE payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reservation_id BIGINT NOT NULL,
    provider VARCHAR(20) NOT NULL,
    payment_reference VARCHAR(80) NOT NULL,
    amount NUMERIC(15, 2) NOT NULL,
    status VARCHAR(20) NOT NULL,
    approved_at TIMESTAMP,
    failed_at TIMESTAMP,
    expired_at TIMESTAMP,
    failure_reason VARCHAR(255),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_payments_reservation_id UNIQUE (reservation_id),
    CONSTRAINT uk_payments_reference UNIQUE (payment_reference),
    CONSTRAINT fk_payments_reservation FOREIGN KEY (reservation_id) REFERENCES reservations (id),
    CONSTRAINT chk_payments_provider CHECK (provider IN ('MOCK')),
    CONSTRAINT chk_payments_status CHECK (status IN ('PENDING', 'SUCCEEDED', 'FAILED', 'CANCELED', 'EXPIRED'))
);

CREATE INDEX idx_payments_status_updated_at ON payments (status, updated_at);

COMMENT ON TABLE payments IS '예약별 결제 정보 및 상태 이력 타임스탬프';
COMMENT ON COLUMN payments.id IS '결제 PK';
COMMENT ON COLUMN payments.reservation_id IS 'reservations.id FK(예약당 1건)';
COMMENT ON COLUMN payments.provider IS '결제 제공자(현재 MOCK)';
COMMENT ON COLUMN payments.payment_reference IS '결제 건을 가리키는 외부 참조 번호. 유일해야 한다.';
COMMENT ON COLUMN payments.amount IS '결제 금액';
COMMENT ON COLUMN payments.status IS '결제 상태(PENDING/SUCCEEDED/FAILED/CANCELED/EXPIRED)';
COMMENT ON COLUMN payments.approved_at IS '승인 시각';
COMMENT ON COLUMN payments.failed_at IS '실패 시각';
COMMENT ON COLUMN payments.expired_at IS '만료 시각';
COMMENT ON COLUMN payments.failure_reason IS '실패 사유 메시지';
COMMENT ON COLUMN payments.created_at IS '생성 시각';
COMMENT ON COLUMN payments.updated_at IS '수정 시각';

---
-- notifications: 사용자 알림
---
CREATE TABLE notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    type VARCHAR(40) NOT NULL,
    title VARCHAR(120) NOT NULL,
    message VARCHAR(500) NOT NULL,
    link VARCHAR(255),
    read_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_notifications_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT chk_notifications_type CHECK (type IN ('RESERVATION_CONFIRMED', 'RESERVATION_CANCELED', 'PAYMENT_FAILED', 'PAYMENT_EXPIRED'))
);

CREATE INDEX idx_notifications_user_read_created ON notifications (user_id, read_at, created_at);

COMMENT ON TABLE notifications IS '사용자 대상 시스템 알림';
COMMENT ON COLUMN notifications.id IS '알림 PK';
COMMENT ON COLUMN notifications.user_id IS '수신자 users.id';
COMMENT ON COLUMN notifications.type IS '알림 타입(예약/결제 이벤트)';
COMMENT ON COLUMN notifications.title IS '알림 제목';
COMMENT ON COLUMN notifications.message IS '알림 본문';
COMMENT ON COLUMN notifications.link IS '클릭 이동 링크(옵션)';
COMMENT ON COLUMN notifications.read_at IS '읽음 처리 시각(NULL이면 미읽음)';
COMMENT ON COLUMN notifications.created_at IS '생성 시각';
COMMENT ON COLUMN notifications.updated_at IS '수정 시각';

-- images 테이블이 없으면 만든다
-- 기존 환경에서 초기 스키마 이력은 있으나 images 테이블이 없는 경우를 복구한다.
-- 컬럼 의미 파악을 돕기 위해 테이블/컬럼 주석과 더미 데이터(1건)를 함께 추가한다.

CREATE TABLE IF NOT EXISTS images (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aggregate_type VARCHAR(30) NOT NULL,
    aggregate_id BIGINT NOT NULL,
    original_filename VARCHAR(255) NOT NULL,
    unique_filename VARCHAR(255) NOT NULL,
    extension VARCHAR(20) NOT NULL,
    file_size BIGINT NOT NULL,
    url VARCHAR(500) NOT NULL,
    sort_order INT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT chk_images_aggregate_type CHECK (aggregate_type IN ('PRODUCT', 'OPTION', 'USER', 'PRODUCT_REVIEW')),
    CONSTRAINT chk_images_sort_order CHECK (sort_order >= 0),
    CONSTRAINT chk_images_file_size CHECK (file_size > 0)
);

CREATE INDEX IF NOT EXISTS idx_images_aggregate ON images (aggregate_type, aggregate_id, sort_order);

---
-- 컬럼 설명 주석
---
COMMENT ON TABLE images IS '도메인 엔티티별 저장 이미지 메타';
COMMENT ON COLUMN images.id IS '이미지 PK(자동 증가)';
COMMENT ON COLUMN images.aggregate_type IS '이미지가 속한 도메인 타입(PRODUCT/OPTION/USER/PRODUCT_REVIEW)';
COMMENT ON COLUMN images.aggregate_id IS 'aggregate_type에 해당하는 실제 엔티티 PK';
COMMENT ON COLUMN images.original_filename IS '사용자가 업로드한 원본 파일명';
COMMENT ON COLUMN images.unique_filename IS '스토리지 저장용 유니크 파일명';
COMMENT ON COLUMN images.extension IS '파일 확장자. jpg, png 등 소문자로 둔다.';
COMMENT ON COLUMN images.file_size IS '파일 크기(byte)';
COMMENT ON COLUMN images.url IS '클라이언트가 접근 가능한 이미지 URL';
COMMENT ON COLUMN images.sort_order IS '동일 엔티티 내 이미지 정렬 순서(0부터)';
COMMENT ON COLUMN images.created_at IS '생성 시각';
COMMENT ON COLUMN images.updated_at IS '수정 시각';

---
-- 더미 데이터
-- images 테이블이 비어있을 때만 1건 삽입한다.
---
INSERT INTO images (
    aggregate_type,
    aggregate_id,
    original_filename,
    unique_filename,
    extension,
    file_size,
    url,
    sort_order,
    created_at,
    updated_at
)
SELECT
    'PRODUCT',
    1,
    'sample-product-image.jpg',
    'sample-product-image-0001.jpg',
    'jpg',
    1024,
    'https://mock-cloud.example/images/sample-product-image-0001.jpg',
    0,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
WHERE NOT EXISTS (SELECT 1 FROM images);

ALTER TABLE user_oauths
    ADD COLUMN profile_name VARCHAR(255);

ALTER TABLE user_oauths
    ADD COLUMN profile_image_url VARCHAR(500);

-- images 테이블 보장
-- 스키마 이력과 달리 테이블만 빠진 데이터베이스를 복구한다. 덤프 복원이나 수동 DDL 누락에 대비한다.
-- 구조만 맞추고 INSERT는 넣지 않는다(운영 데이터 오염 방지).

CREATE TABLE IF NOT EXISTS images (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aggregate_type VARCHAR(30) NOT NULL,
    aggregate_id BIGINT NOT NULL,
    original_filename VARCHAR(255) NOT NULL,
    unique_filename VARCHAR(255) NOT NULL,
    extension VARCHAR(20) NOT NULL,
    file_size BIGINT NOT NULL,
    url VARCHAR(500) NOT NULL,
    sort_order INT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT chk_images_aggregate_type CHECK (aggregate_type IN ('PRODUCT', 'OPTION', 'USER', 'PRODUCT_REVIEW')),
    CONSTRAINT chk_images_sort_order CHECK (sort_order >= 0),
    CONSTRAINT chk_images_file_size CHECK (file_size > 0)
);

CREATE INDEX IF NOT EXISTS idx_images_aggregate ON images (aggregate_type, aggregate_id, sort_order);

COMMENT ON TABLE images IS '도메인 엔티티별 저장 이미지 메타';
COMMENT ON COLUMN images.id IS '이미지 PK(자동 증가)';
COMMENT ON COLUMN images.aggregate_type IS '이미지가 속한 도메인 타입(PRODUCT/OPTION/USER/PRODUCT_REVIEW)';
COMMENT ON COLUMN images.aggregate_id IS 'aggregate_type에 해당하는 실제 엔티티 PK';
COMMENT ON COLUMN images.original_filename IS '사용자가 업로드한 원본 파일명';
COMMENT ON COLUMN images.unique_filename IS '스토리지 저장용 유니크 파일명';
COMMENT ON COLUMN images.extension IS '파일 확장자. jpg, png 등 소문자로 둔다.';
COMMENT ON COLUMN images.file_size IS '파일 크기(byte)';
COMMENT ON COLUMN images.url IS '클라이언트가 접근 가능한 이미지 URL';
COMMENT ON COLUMN images.sort_order IS '동일 엔티티 내 이미지 정렬 순서(0부터)';
COMMENT ON COLUMN images.created_at IS '생성 시각';
COMMENT ON COLUMN images.updated_at IS '수정 시각';

ALTER TABLE users
    ADD COLUMN profile_image_url VARCHAR(500) NULL;

ALTER TABLE users
    ADD COLUMN password_hash VARCHAR(255) NULL;

COMMENT ON COLUMN users.password_hash IS '로컬 가입 비밀번호(BCrypt). OAuth 전용 계정은 NULL';

DROP INDEX IF EXISTS idx_users_email;

CREATE UNIQUE INDEX uq_users_email ON users (email);

CREATE UNIQUE INDEX uq_users_nickname ON users (nickname);

-- 리뷰 신뢰도: 예약 연동, 도움돼요, 신고/숨김

ALTER TABLE product_reviews ADD COLUMN reservation_id BIGINT NULL;
ALTER TABLE product_reviews ADD COLUMN helpful_count BIGINT NOT NULL DEFAULT 0;
ALTER TABLE product_reviews ADD COLUMN hidden_at TIMESTAMP NULL;
ALTER TABLE product_reviews ADD COLUMN hidden_reason VARCHAR(80) NULL;

ALTER TABLE product_reviews ADD CONSTRAINT fk_product_reviews_reservation
    FOREIGN KEY (reservation_id) REFERENCES reservations (id);

CREATE UNIQUE INDEX uk_product_reviews_reservation_id ON product_reviews (reservation_id);

COMMENT ON COLUMN product_reviews.reservation_id IS '방문 완료 예약 FK(인증 리뷰)';
COMMENT ON COLUMN product_reviews.helpful_count IS '도움돼요 수(비정규화)';
COMMENT ON COLUMN product_reviews.hidden_at IS '신고 등으로 비공개 처리 시각';
COMMENT ON COLUMN product_reviews.hidden_reason IS '숨김 사유';

CREATE TABLE product_review_helpful_votes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    review_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_review_helpful_user UNIQUE (review_id, user_id),
    CONSTRAINT fk_helpful_review FOREIGN KEY (review_id) REFERENCES product_reviews (id) ON DELETE CASCADE,
    CONSTRAINT fk_helpful_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE INDEX idx_helpful_review_id ON product_review_helpful_votes (review_id);

CREATE TABLE product_review_reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    review_id BIGINT NOT NULL,
    reporter_user_id BIGINT NOT NULL,
    reason VARCHAR(200) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_review_report_user UNIQUE (review_id, reporter_user_id),
    CONSTRAINT fk_report_review FOREIGN KEY (review_id) REFERENCES product_reviews (id) ON DELETE CASCADE,
    CONSTRAINT fk_report_reporter FOREIGN KEY (reporter_user_id) REFERENCES users (id)
);

CREATE INDEX idx_report_review_id ON product_review_reports (review_id);

COMMENT ON TABLE product_review_helpful_votes IS '리뷰 도움돼요(사용자당 1회 토글)';
COMMENT ON TABLE product_review_reports IS '리뷰 신고';

-- 매진 슬롯 웨이팅: 취소·만료·결제 실패 등으로 빈자리가 나면 대기자에게 알림

CREATE TABLE reservation_slot_waitlist (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    reservation_slot_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_rsw_user_slot UNIQUE (user_id, reservation_slot_id),
    CONSTRAINT fk_rsw_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_rsw_slot FOREIGN KEY (reservation_slot_id) REFERENCES reservation_slots (id) ON DELETE CASCADE
);

CREATE INDEX idx_rsw_slot ON reservation_slot_waitlist (reservation_slot_id);
CREATE INDEX idx_rsw_user ON reservation_slot_waitlist (user_id);

COMMENT ON TABLE reservation_slot_waitlist IS '매진/선점 중인 슬롯 빈자리 알림 대기';
COMMENT ON COLUMN reservation_slot_waitlist.user_id IS 'users.id';
COMMENT ON COLUMN reservation_slot_waitlist.reservation_slot_id IS 'reservation_slots.id';

-- 결제대행사 연동에 맞춘 결제 스키마 확장
-- payments: 가맹점 주문 번호, 대행사 키, 오류 정보, 응답 본문, 중복 방지 키 등
-- payment_logs: 승인·취소·서버 알림 요청과 응답, 예외 기록
-- - payment_refunds: 환불(취소) 시도 이력
-- 기존 행에 결제 번호와 주문 식별자를 채운 뒤 필수로 만들고, 제공자와 상태 검사 규칙을 바꾼다.

---
-- 결제 제공자와 상태 코드 목록을 애플리케이션 규칙에 맞게 다시 정한다
---
ALTER TABLE payments DROP CONSTRAINT chk_payments_provider;
ALTER TABLE payments DROP CONSTRAINT chk_payments_status;

---
-- payments: 대행사 연동용 컬럼을 추가한다
---
ALTER TABLE payments ADD COLUMN payment_no VARCHAR(64) NULL;
ALTER TABLE payments ADD COLUMN order_id VARCHAR(200) NULL;
ALTER TABLE payments ADD COLUMN payment_key VARCHAR(200) NULL;

ALTER TABLE payments ADD COLUMN order_name VARCHAR(255) NULL;
ALTER TABLE payments ADD COLUMN supplied_amount NUMERIC(15, 2) NULL;
ALTER TABLE payments ADD COLUMN vat NUMERIC(15, 2) NULL;
ALTER TABLE payments ADD COLUMN tax_free_amount NUMERIC(15, 2) NULL;
ALTER TABLE payments ADD COLUMN currency VARCHAR(10) NULL;
ALTER TABLE payments ADD COLUMN gateway_method VARCHAR(50) NULL;
ALTER TABLE payments ADD COLUMN gateway_type VARCHAR(50) NULL;
ALTER TABLE payments ADD COLUMN external_status VARCHAR(50) NULL;

ALTER TABLE payments ADD COLUMN requested_at TIMESTAMP NULL;
ALTER TABLE payments ADD COLUMN last_transaction_key VARCHAR(200) NULL;
ALTER TABLE payments ADD COLUMN fail_code VARCHAR(100) NULL;

ALTER TABLE payments ADD COLUMN canceled_at TIMESTAMP NULL;
ALTER TABLE payments ADD COLUMN cancel_amount NUMERIC(15, 2) NOT NULL DEFAULT 0;

ALTER TABLE payments ADD COLUMN card_company VARCHAR(100) NULL;
ALTER TABLE payments ADD COLUMN card_number VARCHAR(50) NULL;
ALTER TABLE payments ADD COLUMN installment_plan_months INT NULL;
ALTER TABLE payments ADD COLUMN is_interest_free BOOLEAN NULL;

ALTER TABLE payments ADD COLUMN virtual_account_bank VARCHAR(100) NULL;
ALTER TABLE payments ADD COLUMN virtual_account_number VARCHAR(100) NULL;
ALTER TABLE payments ADD COLUMN virtual_account_due_date TIMESTAMP NULL;

ALTER TABLE payments ADD COLUMN easy_pay_provider VARCHAR(100) NULL;

ALTER TABLE payments ADD COLUMN raw_response_json LONGVARCHAR NULL;
ALTER TABLE payments ADD COLUMN idempotency_key VARCHAR(100) NULL;

-- 기존 결제 행에 내부 번호와 가맹점 주문 번호를 채운다
UPDATE payments SET payment_no = 'LEGACY-' || CAST(id AS VARCHAR(30)) WHERE payment_no IS NULL;
UPDATE payments SET order_id = payment_reference WHERE order_id IS NULL;

ALTER TABLE payments ALTER COLUMN payment_no SET NOT NULL;
ALTER TABLE payments ALTER COLUMN order_id SET NOT NULL;

-- 내부 결제 번호, 가맹점 주문 번호, 대행사 결제 키, 승인 시 중복 방지 키는 각각 유일해야 한다
ALTER TABLE payments ADD CONSTRAINT uk_payments_payment_no UNIQUE (payment_no);
ALTER TABLE payments ADD CONSTRAINT uk_payments_order_id UNIQUE (order_id);
ALTER TABLE payments ADD CONSTRAINT uk_payments_payment_key UNIQUE (payment_key);
ALTER TABLE payments ADD CONSTRAINT uk_payments_idempotency_key UNIQUE (idempotency_key);

ALTER TABLE payments ADD CONSTRAINT chk_payments_provider CHECK (provider IN ('MOCK', 'TOSS'));
ALTER TABLE payments ADD CONSTRAINT chk_payments_status CHECK (
    status IN ('PENDING', 'SUCCEEDED', 'FAILED', 'CANCELED', 'EXPIRED', 'REFUNDED', 'PARTIAL_CANCELED')
);

-- 결제 상태와 키로 빠르게 찾기 위한 인덱스
CREATE INDEX idx_payments_external_status ON payments (external_status);
CREATE INDEX idx_payments_payment_key ON payments (payment_key);

COMMENT ON TABLE payments IS '예약 단위 결제 정보와 상태 이력. 결제대행사 승인·환불·응답 본문·중복 방지 키를 담는다.';
COMMENT ON COLUMN payments.payment_no IS '내부 결제 번호(유니크)';
COMMENT ON COLUMN payments.order_id IS '가맹점 주문 식별자. 대행사 orderId와 맞추며 유일해야 한다.';
COMMENT ON COLUMN payments.payment_key IS '결제대행사가 내려준 결제 건 고유 키. 승인이 끝난 뒤 채운다.';
COMMENT ON COLUMN payments.order_name IS '주문명. 대행사 orderName에 대응한다.';
COMMENT ON COLUMN payments.supplied_amount IS '공급가액.';
COMMENT ON COLUMN payments.vat IS '부가세.';
COMMENT ON COLUMN payments.tax_free_amount IS '비과세 금액.';
COMMENT ON COLUMN payments.currency IS '통화 코드. ISO 4217 규칙을 따른다.';
COMMENT ON COLUMN payments.gateway_method IS '결제 수단 요약. 대행사 method에 대응한다.';
COMMENT ON COLUMN payments.gateway_type IS '결제 유형 코드. NORMAL 같은 값을 쓴다.';
COMMENT ON COLUMN payments.external_status IS '대행사가 내려준 결제 상태 문자열.';
COMMENT ON COLUMN payments.requested_at IS '결제 요청 시각.';
COMMENT ON COLUMN payments.last_transaction_key IS '마지막 거래 식별 키.';
COMMENT ON COLUMN payments.fail_code IS '실패 코드.';
COMMENT ON COLUMN payments.canceled_at IS '전액 취소 완료 시각(내부 마킹)';
COMMENT ON COLUMN payments.cancel_amount IS '누적 취소(환불) 금액';
COMMENT ON COLUMN payments.card_company IS '카드사 이름.';
COMMENT ON COLUMN payments.card_number IS '마스킹된 카드번호.';
COMMENT ON COLUMN payments.installment_plan_months IS '할부 개월 수';
COMMENT ON COLUMN payments.is_interest_free IS '무이자 여부';
COMMENT ON COLUMN payments.virtual_account_bank IS '가상계좌 은행';
COMMENT ON COLUMN payments.virtual_account_number IS '가상계좌 번호';
COMMENT ON COLUMN payments.virtual_account_due_date IS '가상계좌 입금 만료 시각';
COMMENT ON COLUMN payments.easy_pay_provider IS '간편결제 제공자.';
COMMENT ON COLUMN payments.raw_response_json IS '승인 또는 오류 응답 본문 JSON.';
COMMENT ON COLUMN payments.idempotency_key IS '승인 요청마다 다른 중복 방지 키. 유일해야 한다.';

---
-- payment_logs: 승인·취소·서버 알림 요청과 응답, 예외 기록
---
CREATE TABLE payment_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_id BIGINT NULL,
    order_id VARCHAR(200) NULL,
    payment_key VARCHAR(200) NULL,
    log_type VARCHAR(50) NOT NULL,
    step VARCHAR(50) NULL,
    request_url VARCHAR(500) NULL,
    http_method VARCHAR(20) NULL,
    http_status INT NULL,
    request_body LONGVARCHAR NULL,
    response_body LONGVARCHAR NULL,
    error_code VARCHAR(100) NULL,
    error_message VARCHAR(1000) NULL,
    stack_trace LONGVARCHAR NULL,
    client_ip VARCHAR(100) NULL,
    user_agent VARCHAR(500) NULL,
    trace_id VARCHAR(100) NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_payment_logs_payment FOREIGN KEY (payment_id) REFERENCES payments (id) ON DELETE SET NULL,
    CONSTRAINT chk_payment_logs_type CHECK (
        log_type IN (
            'CONFIRM_REQUEST', 'CONFIRM_RESPONSE', 'CONFIRM_ERROR',
            'CANCEL_REQUEST', 'CANCEL_RESPONSE', 'CANCEL_ERROR',
            'WEBHOOK_RECEIVED', 'WEBHOOK_REJECTED', 'MOCK_WEBHOOK', 'SYSTEM'
        )
    ),
    CONSTRAINT chk_payment_logs_step CHECK (step IS NULL OR step IN ('CLIENT', 'SERVER', 'TOSS_API'))
);

CREATE INDEX idx_payment_logs_payment_id ON payment_logs (payment_id);
CREATE INDEX idx_payment_logs_order_id ON payment_logs (order_id);
CREATE INDEX idx_payment_logs_created_at ON payment_logs (created_at);

COMMENT ON TABLE payment_logs IS '결제 승인·취소·서버 알림 요청과 응답, 오류를 남긴다.';
COMMENT ON COLUMN payment_logs.id IS '로그 PK';
COMMENT ON COLUMN payment_logs.payment_id IS 'payments.id FK(삭제 시 NULL)';
COMMENT ON COLUMN payment_logs.order_id IS '주문 식별자 검색용.';
COMMENT ON COLUMN payment_logs.payment_key IS '결제대행사가 내려준 결제 건 고유 키';
COMMENT ON COLUMN payment_logs.log_type IS 'CONFIRM_*/CANCEL_*/WEBHOOK_*/MOCK_WEBHOOK/SYSTEM';
COMMENT ON COLUMN payment_logs.step IS 'CLIENT / SERVER / TOSS_API';
COMMENT ON COLUMN payment_logs.request_url IS '호출 URL 경로';
COMMENT ON COLUMN payment_logs.http_method IS 'HTTP 메서드';
COMMENT ON COLUMN payment_logs.http_status IS 'HTTP 응답 상태 코드';
COMMENT ON COLUMN payment_logs.request_body IS '요청 본문(JSON 등)';
COMMENT ON COLUMN payment_logs.response_body IS '응답 본문(JSON 등)';
COMMENT ON COLUMN payment_logs.error_code IS '에러 코드';
COMMENT ON COLUMN payment_logs.error_message IS '에러 메시지';
COMMENT ON COLUMN payment_logs.stack_trace IS '예외 스택(내부 오류 시)';
COMMENT ON COLUMN payment_logs.client_ip IS '클라이언트 IP';
COMMENT ON COLUMN payment_logs.user_agent IS 'User-Agent';
COMMENT ON COLUMN payment_logs.trace_id IS '요청 추적 ID(X-Trace-Id 등)';
COMMENT ON COLUMN payment_logs.created_at IS '생성 시각';
COMMENT ON COLUMN payment_logs.updated_at IS '수정 시각';

---
-- payment_refunds: 환불·취소 API 호출 단위 이력. 실패 시 재시도와 고객 응대에 쓴다
---
CREATE TABLE payment_refunds (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_id BIGINT NOT NULL,
    reservation_id BIGINT NOT NULL,
    cancel_amount NUMERIC(15, 2) NOT NULL,
    cancel_reason VARCHAR(500) NOT NULL,
    status VARCHAR(30) NOT NULL,
    requested_by VARCHAR(20) NOT NULL,
    external_transaction_key VARCHAR(200) NULL,
    fail_code VARCHAR(100) NULL,
    fail_message VARCHAR(500) NULL,
    idempotency_key VARCHAR(100) NULL,
    raw_response_json LONGVARCHAR NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_payment_refunds_payment FOREIGN KEY (payment_id) REFERENCES payments (id),
    CONSTRAINT fk_payment_refunds_reservation FOREIGN KEY (reservation_id) REFERENCES reservations (id),
    CONSTRAINT uk_payment_refunds_idempotency UNIQUE (idempotency_key),
    CONSTRAINT chk_payment_refunds_status CHECK (status IN ('PENDING', 'SUCCEEDED', 'FAILED')),
    CONSTRAINT chk_payment_refunds_requested_by CHECK (requested_by IN ('USER', 'ADMIN', 'SYSTEM', 'WEBHOOK'))
);

CREATE INDEX idx_payment_refunds_payment_id ON payment_refunds (payment_id);
CREATE INDEX idx_payment_refunds_reservation_id ON payment_refunds (reservation_id);
CREATE INDEX idx_payment_refunds_status ON payment_refunds (status);

COMMENT ON TABLE payment_refunds IS '결제대행사 환불·취소 요청 이력. 고객 지원과 재시도 추적에 쓴다.';
COMMENT ON COLUMN payment_refunds.id IS '환불 이력 PK';
COMMENT ON COLUMN payment_refunds.payment_id IS 'payments.id FK';
COMMENT ON COLUMN payment_refunds.reservation_id IS 'reservations.id FK(조회 편의)';
COMMENT ON COLUMN payment_refunds.cancel_amount IS '해당 요청 취소(환불) 금액';
COMMENT ON COLUMN payment_refunds.cancel_reason IS '취소 사유. 사용자·운영·시스템이 남긴 문구.';
COMMENT ON COLUMN payment_refunds.status IS 'PENDING / SUCCEEDED / FAILED';
COMMENT ON COLUMN payment_refunds.requested_by IS 'USER / ADMIN / SYSTEM / WEBHOOK';
COMMENT ON COLUMN payment_refunds.external_transaction_key IS '대행사 거래 식별 키.';
COMMENT ON COLUMN payment_refunds.fail_code IS '실패 코드.';
COMMENT ON COLUMN payment_refunds.fail_message IS '실패 메시지.';
COMMENT ON COLUMN payment_refunds.idempotency_key IS '취소 요청 중복 방지 키. 유일해야 한다.';
COMMENT ON COLUMN payment_refunds.raw_response_json IS '취소 응답 본문 JSON.';
COMMENT ON COLUMN payment_refunds.created_at IS '생성 시각';
COMMENT ON COLUMN payment_refunds.updated_at IS '수정 시각';

-- 알림 수신 설정과 만료 임박 알림 타입
-- notifications에 만료 임박 타입을 추가로 허용한다.
-- 사용자마다 알림 종류별로 받을지 여부를 저장한다.
-- 배치나 서비스는 꺼 둔 타입은 보내지 않도록 이 테이블을 본다.
-- 아래 문자열은 알림 종류 코드이다.
-- RESERVATION_CONFIRMED 예약 확정
-- RESERVATION_CANCELED 예약 취소
-- PAYMENT_FAILED 결제 실패
-- PAYMENT_EXPIRED 결제 기한 만료
-- RESERVATION_SLOT_AVAILABLE 예약 가능 슬롯 알림
-- RESERVATION_EXPIRING_SOON 예약/결제 등 만료 임박

---
-- notifications: 허용되는 알림 type 목록을 갱신한다
-- 만료 임박 알림 타입을 허용 목록에 넣는다
---
ALTER TABLE notifications DROP CONSTRAINT IF EXISTS chk_notifications_type;
ALTER TABLE notifications ADD CONSTRAINT chk_notifications_type CHECK (
    type IN (
        'RESERVATION_CONFIRMED',
        'RESERVATION_CANCELED',
        'PAYMENT_FAILED',
        'PAYMENT_EXPIRED',
        'RESERVATION_SLOT_AVAILABLE',
        'RESERVATION_EXPIRING_SOON'
    )
);

---
-- notification_preferences: 사용자마다 알림 종류별 수신 여부
-- user_id와 type 조합은 한 번만 등장한다
---
CREATE TABLE IF NOT EXISTS notification_preferences (
 -- 내부 순번 기본 키
    id           BIGINT        NOT NULL GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
 -- users.id 외래 키
    user_id      BIGINT        NOT NULL,
 -- 알림 종류 코드
    type         VARCHAR(40)   NOT NULL,
 -- true면 해당 타입 알림을 받고, false면 받지 않는다
    enabled      BOOLEAN       NOT NULL DEFAULT TRUE,
    created_at   TIMESTAMP(6)  NOT NULL,
    updated_at   TIMESTAMP(6)  NOT NULL,
    CONSTRAINT uk_np_user_type UNIQUE (user_id, type),
    CONSTRAINT fk_np_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT chk_np_type CHECK (
        type IN (
            'RESERVATION_CONFIRMED',
            'RESERVATION_CANCELED',
            'PAYMENT_FAILED',
            'PAYMENT_EXPIRED',
            'RESERVATION_SLOT_AVAILABLE',
            'RESERVATION_EXPIRING_SOON'
        )
    )
);

-- 사용자 기준 설정 조회·배치 스캔용
CREATE INDEX IF NOT EXISTS idx_np_user_id ON notification_preferences (user_id);

-- 관리자 감사 로그
-- 예약 취소, 슬롯 일괄 생성·삭제, 상품·옵션 삭제 같은 관리 작업을 한 행으로 남긴다.
-- 운영 추적과 사후 조사용이며 서버가 기록한다.
-- 인덱스는 최근 시각 내림차순 조회와 관리자별 필터에 맞춘다.

CREATE TABLE IF NOT EXISTS admin_audit_logs (
    id             BIGINT        NOT NULL GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    admin_user_id  BIGINT        NOT NULL,
    action_code    VARCHAR(64)   NOT NULL,
    target_type    VARCHAR(64)   NOT NULL,
    target_id      BIGINT,
    detail         VARCHAR(2000),
    created_at     TIMESTAMP(6)  NOT NULL,
    CONSTRAINT fk_admin_audit_logs_user FOREIGN KEY (admin_user_id) REFERENCES users (id)
);

CREATE INDEX IF NOT EXISTS idx_admin_audit_logs_created_at ON admin_audit_logs (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_admin_audit_logs_admin_user ON admin_audit_logs (admin_user_id);

COMMENT ON TABLE admin_audit_logs IS '관리자 운영 액션 감사 로그';

COMMENT ON COLUMN admin_audit_logs.id IS '로그 PK 자동 증가';
COMMENT ON COLUMN admin_audit_logs.admin_user_id IS '행동한 관리자 users.id FK';
COMMENT ON COLUMN admin_audit_logs.action_code IS '비즈니스 액션 코드 예 RESERVATION_CANCEL SLOTS_BULK_CREATE';
COMMENT ON COLUMN admin_audit_logs.target_type IS '대상 도메인 유형 예 RESERVATION PRODUCT RESERVATION_SLOT OPTION';
COMMENT ON COLUMN admin_audit_logs.target_id IS '대상 엔티티 PK 없으면 null';
COMMENT ON COLUMN admin_audit_logs.detail IS '추가 맥락 짧은 JSON 또는 문장 최대 2000자';
COMMENT ON COLUMN admin_audit_logs.created_at IS '기록 시각';

COMMENT ON INDEX idx_admin_audit_logs_created_at IS '최근 로그 목록 조회용';
COMMENT ON INDEX idx_admin_audit_logs_admin_user IS '관리자별 로그 조회용';

-- 리뷰 반응·신고 테이블에 수정 시각 컬럼이 없으면 추가한다. 애플리케이션과 스키마를 맞추기 위함이다.
-- 기존 데이터는 마이그레이션 시점 시각으로 채우고, 이후 값은 애플리케이션 감사 로직이 갱신한다.

ALTER TABLE product_review_helpful_votes
    ADD COLUMN updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6);

ALTER TABLE product_review_reports
    ADD COLUMN updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6);

-- 기사·본문 섹션·갤러리·태그
-- 계층: webzine_issues → webzine_articles → sections / gallery_images / tags
-- 이슈: 권호(volume)·슬러그·발행일·커버/티저 등 메타
-- 기사: 이슈 소속, 목록/상세용 slug·요약·히어로/카드 이미지, 저자·크레딧
-- ON DELETE CASCADE: 이슈/기사 삭제 시 하위 행 정리

-- 웹진 호(이슈): URL용 slug, 정수 권호(volume)는 각각 유일
create table if not exists webzine_issues (
    id bigint generated by default as identity primary key,
    slug varchar(80) not null, -- 공개 URL 경로용 고유 식별자
    volume integer not null, -- 인쇄물 스타일 권호(1, 2, 3, …)
    issue_date date not null, -- 발행일(표시·정렬)
    cover_image_url varchar(500) not null, -- 표지 이미지 URL
    teaser varchar(1000) not null, -- 목록/공유용 짧은 소개
    created_at timestamp not null default current_timestamp, -- 생성 시각
    updated_at timestamp not null default current_timestamp, -- 마지막 수정 시각
    constraint uk_webzine_issue_slug unique (slug),
    constraint uk_webzine_issue_volume unique (volume)
);

-- 기사: 이슈당 slug 유일
create table if not exists webzine_articles (
    id bigint generated by default as identity primary key,
    issue_id bigint not null references webzine_issues(id) on delete cascade, -- 소속 이슈
    slug varchar(150) not null, -- 기사별 URL 슬러그(이슈 내 유일)
    title varchar(200) not null, -- 제목
    kicker varchar(200) not null, -- 상단 작은 헤드라인/카테고리 톤
    summary text not null, -- 요약/리드
    hero_image_url varchar(500) not null, -- 상단 풀폭 이미지
    card_image_url varchar(500) not null, -- 목록 카드 썸네일
    category varchar(30) not null, -- 분류 키
    format_label varchar(60) not null, -- 인터뷰/리포트 등 포맷 라벨
    author_name varchar(120) not null, -- 표시용 저자명
    author_email varchar(255) not null, -- 연락/메타용 이메일
    credit_line varchar(255) not null, -- 사진·출처 등
    highlight_quote varchar(500), -- 인용 강조(옵션)
    created_at timestamp not null default current_timestamp, -- 생성 시각
    updated_at timestamp not null default current_timestamp, -- 마지막 수정 시각
    constraint uk_webzine_article_issue_slug unique (issue_id, slug)
);

-- 이슈별 기사 목록 조회용
create index if not exists idx_webzine_articles_issue_id on webzine_articles(issue_id);

-- 기사 본문을 순서 있는 블록(섹션)으로 분리
create table if not exists webzine_article_sections (
    id bigint generated by default as identity primary key,
    article_id bigint not null references webzine_articles(id) on delete cascade, -- 소속 기사
    display_order integer not null, -- 렌더 순서
    heading varchar(200), -- 소제목(없으면 null)
    body text not null, -- 본문(표현 형식은 애플리케이션 규약)
    note varchar(1000), -- 각주·편집자 주(옵션)
    created_at timestamp not null default current_timestamp, -- 생성 시각
    updated_at timestamp not null default current_timestamp, -- 마지막 수정 시각
    constraint uk_webzine_article_section_order unique (article_id, display_order)
);

-- 기사 하단 갤러리 이미지
create table if not exists webzine_article_gallery_images (
    id bigint generated by default as identity primary key,
    article_id bigint not null references webzine_articles(id) on delete cascade, -- 소속 기사
    display_order integer not null, -- 갤러리 내 순서
    image_url varchar(500) not null, -- 이미지 URL
    created_at timestamp not null default current_timestamp, -- 생성 시각
    updated_at timestamp not null default current_timestamp, -- 마지막 수정 시각
    constraint uk_webzine_article_gallery_order unique (article_id, display_order)
);

-- 기사 태그
create table if not exists webzine_article_tags (
    id bigint generated by default as identity primary key,
    article_id bigint not null references webzine_articles(id) on delete cascade, -- 소속 기사
    display_order integer not null, -- 태그 나열 순서
    tag_name varchar(80) not null, -- 태그 문자열
    created_at timestamp not null default current_timestamp, -- 생성 시각
    updated_at timestamp not null default current_timestamp, -- 마지막 수정 시각
    constraint uk_webzine_article_tag_name unique (article_id, tag_name)
);

-- Newsletter admin domain tables
-- 뉴스레터 본문은 문단 단위로 정규화하여 목록/상세/관리 화면에서 재사용한다.

-- 뉴스레터 마스터
create table if not exists newsletters (
    id bigint generated by default as identity primary key,
    slug varchar(160) not null,
    title varchar(200) not null,
    category_label varchar(80) not null,
    published_at date not null,
    image_url varchar(500) not null,
    summary text not null,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,
    constraint uk_newsletter_slug unique (slug)
);

-- 뉴스레터 태그
create table if not exists newsletter_tags (
    id bigint generated by default as identity primary key,
    newsletter_id bigint not null references newsletters(id) on delete cascade,
    display_order integer not null,
    tag_name varchar(80) not null,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,
    constraint uk_newsletter_tag_name unique (newsletter_id, tag_name)
);

-- 뉴스레터 문단
create table if not exists newsletter_paragraphs (
    id bigint generated by default as identity primary key,
    newsletter_id bigint not null references newsletters(id) on delete cascade,
    display_order integer not null,
    body text not null,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,
    constraint uk_newsletter_paragraph_order unique (newsletter_id, display_order)
);

-- 발행일 최신순 조회 인덱스
create index if not exists idx_newsletters_published_at on newsletters(published_at);

-- 구독자 및 콘텐츠 발송 이력 테이블
-- 이메일 구독 상태(동의/활성 여부)와 뉴스레터·웹진 발송 결과를 추적한다.
-- 같은 콘텐츠를 같은 채널로 두 번 기록하지 않도록 유일 제약을 둔다.

create table if not exists email_subscriptions (
    id bigint generated by default as identity primary key,
    email varchar(255) not null, -- 구독자 이메일(유일)
    subscribed_newsletters boolean not null default true,
    subscribed_issues boolean not null default true,
    consented_at timestamp not null,
    subscribed_at timestamp not null,
    subscription_source varchar(50) not null, -- 구독 유입 채널
    active boolean not null default true,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,
    constraint uk_email_subscriptions_email unique (email)
);

create table if not exists subscription_dispatch_histories (
    id bigint generated by default as identity primary key,
    content_type varchar(40) not null,
    content_slug varchar(160) not null,
    content_title varchar(255) not null,
    content_summary varchar(1000),
    dispatch_channel varchar(20) not null,
    dispatch_status varchar(20) not null, -- 발송 상태 코드. SENT, FAILED 등
    recipient_count bigint not null,
    content_created_at timestamp,
    dispatched_at timestamp not null,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,
    constraint uk_subscription_dispatch_content unique (content_type, content_slug, dispatch_channel)
);

comment on table email_subscriptions is '구독자 마스터 테이블(수신 동의/활성 상태 포함)';
comment on column email_subscriptions.email is '구독자 이메일(전역 유일)';
comment on column email_subscriptions.subscribed_newsletters is '뉴스레터 수신 여부';
comment on column email_subscriptions.subscribed_issues is '웹진/이슈 수신 여부';
comment on column email_subscriptions.consented_at is '수신 동의 시각';
comment on column email_subscriptions.subscribed_at is '구독 등록 시각';
comment on column email_subscriptions.subscription_source is '구독 유입 채널';
comment on column email_subscriptions.active is '활성 구독 상태';
comment on column email_subscriptions.created_at is '생성 시각';
comment on column email_subscriptions.updated_at is '마지막 수정 시각';

comment on table subscription_dispatch_histories is '콘텐츠 발송 이력 테이블';
comment on column subscription_dispatch_histories.content_type is '콘텐츠 유형 코드. NEWSLETTER, WEBZINE 등 서비스에서 정의한 값.';
comment on column subscription_dispatch_histories.content_slug is '콘텐츠 고유 slug/키';
comment on column subscription_dispatch_histories.content_title is '발송 당시 제목 스냅샷';
comment on column subscription_dispatch_histories.content_summary is '발송 당시 요약 스냅샷';
comment on column subscription_dispatch_histories.dispatch_channel is '발송 채널 코드. EMAIL 등.';
comment on column subscription_dispatch_histories.dispatch_status is '발송 상태 코드. SENT, FAILED 등.';
comment on column subscription_dispatch_histories.recipient_count is '발송 대상자 수';
comment on column subscription_dispatch_histories.content_created_at is '콘텐츠 원본 생성 시각';
comment on column subscription_dispatch_histories.dispatched_at is '실제 발송 시각';
comment on column subscription_dispatch_histories.created_at is '생성 시각';
comment on column subscription_dispatch_histories.updated_at is '마지막 수정 시각';

create index if not exists idx_email_subscriptions_active on email_subscriptions(active);
create index if not exists idx_subscription_dispatch_histories_dispatched_at on subscription_dispatch_histories(dispatched_at);

-- 사이트 도메인(tb_domain_list), 배너(tb_banner), 팝업(tb_popup_manage),
-- 메인 이미지(tb_main_image) 등. MySQL·PostgreSQL 각각의 dialect 스크립트와 논리 구조를 맞춘다.
-- 루트 경로의 스크립트만 쓰는 로컬·테스트 구성에서 이 블록이 실행된다.
-- 데이터베이스 종류별 전용 스크립트만 넣은 경우에는 그쪽이 대신 실행될 수 있다.
-- 시드: ON CONFLICT 대신 INSERT ... SELECT ... WHERE NOT EXISTS 로
-- 로 동일 PK 가 있으면 건너뜀.

---
-- tb_domain_list: 멀티 사이트 구분용 도메인 마스터
---
create table if not exists tb_domain_list (
    domain_id varchar(20) primary key,
    domain_nm varchar(100),
    domain_path varchar(200),
    domain_dc varchar(500),
    use_at char(1) default 'Y',
    actvty_at char(1) default 'Y',
    sort_seq integer default 0
);

comment on table tb_domain_list is '사이트·언어 도메인 목록. 배너·팝업·메인 이미지가 함께 참조한다.';
comment on column tb_domain_list.domain_id is '사이트 도메인 식별자. kr, en처럼 짧은 코드로 구분한다.';
comment on column tb_domain_list.domain_nm is '표시명';
comment on column tb_domain_list.domain_path is 'URL 경로 프리픽스 등';
comment on column tb_domain_list.domain_dc is '설명';
comment on column tb_domain_list.use_at is '사용 여부 Y/N';
comment on column tb_domain_list.actvty_at is '활성 여부 Y/N';
comment on column tb_domain_list.sort_seq is '정렬 순서';

---
-- tb_banner: 상단·슬롯 등 배너 콘텐츠
---
create table if not exists tb_banner (
    banner_id varchar(20) primary key,
    domain_id varchar(20) default 'kr',
    banner_nm varchar(200),
    link_url varchar(500),
    banner_image varchar(500),
    banner_image_file varchar(500),
    banner_dc varchar(1000),
    sort_ordr integer default 0,
    reflct_at char(1) default 'Y',
    frst_register_id varchar(50),
    frst_regist_pnttm timestamp default current_timestamp,
    last_updusr_id varchar(50),
    last_updt_pnttm timestamp,
    constraint fk_tb_banner_domain foreign key (domain_id) references tb_domain_list (domain_id)
);

comment on table tb_banner is '배너 관리';
comment on column tb_banner.banner_id is '배너 PK (애플리케이션에서 BNR_ 접두 + 타임스탬프 등)';
comment on column tb_banner.domain_id is 'tb_domain_list 참조';
comment on column tb_banner.banner_nm is '배너명';
comment on column tb_banner.link_url is '클릭 시 이동 URL';
comment on column tb_banner.banner_image is '이미지 경로/URL';
comment on column tb_banner.banner_image_file is '원본 파일명 등';
comment on column tb_banner.banner_dc is '설명';
comment on column tb_banner.sort_ordr is '노출 정렬 순서';
comment on column tb_banner.reflct_at is '게시(반영) 여부 Y/N';
comment on column tb_banner.frst_register_id is '최초 등록자';
comment on column tb_banner.frst_regist_pnttm is '최초 등록 일시';
comment on column tb_banner.last_updusr_id is '최종 수정자';
comment on column tb_banner.last_updt_pnttm is '최종 수정 일시';

---
-- tb_popup_manage: 기간·위치 속성을 가진 팝업
---
create table if not exists tb_popup_manage (
    popup_id varchar(20) primary key,
    domain_id varchar(20) default 'kr',
    popup_sj_nm varchar(200),
    file_url varchar(500),
    link_target varchar(20) default '_blank',
    popup_img_path varchar(500),
    popup_file_nm varchar(200),
    popup_vrticl_lc integer default 0,
    popup_width_lc integer default 0,
    popup_vrticl_size integer default 400,
    popup_width_size integer default 500,
    ntce_bgnde varchar(20),
    ntce_endde varchar(20),
    stopvew_setup_at char(1) default 'Y',
    ntce_at char(1) default 'Y',
    frst_register_id varchar(50),
    frst_regist_pnttm timestamp default current_timestamp,
    last_updusr_id varchar(50),
    last_updt_pnttm timestamp,
    constraint fk_tb_popup_domain foreign key (domain_id) references tb_domain_list (domain_id)
);

comment on table tb_popup_manage is '팝업 관리';
comment on column tb_popup_manage.popup_id is '팝업 PK';
comment on column tb_popup_manage.domain_id is 'tb_domain_list 참조';
comment on column tb_popup_manage.popup_sj_nm is '팝업 제목';
comment on column tb_popup_manage.file_url is '링크 URL';
comment on column tb_popup_manage.link_target is 'a 태그 target (_blank, _self 등)';
comment on column tb_popup_manage.popup_img_path is '팝업 이미지 경로';
comment on column tb_popup_manage.popup_file_nm is '이미지 파일명';
comment on column tb_popup_manage.popup_vrticl_lc is '세로 위치';
comment on column tb_popup_manage.popup_width_lc is '가로 위치';
comment on column tb_popup_manage.popup_vrticl_size is '세로 크기(px)';
comment on column tb_popup_manage.popup_width_size is '가로 크기(px)';
comment on column tb_popup_manage.ntce_bgnde is '게시 시작 일시. 문자열로 저장하는 기존 운영 규격과 맞춘다';
comment on column tb_popup_manage.ntce_endde is '게시 종료일시';
comment on column tb_popup_manage.stopvew_setup_at is '다시보지 않기 설정 사용 여부 Y/N';
comment on column tb_popup_manage.ntce_at is '게시(알림) 여부 Y/N';
comment on column tb_popup_manage.frst_register_id is '최초 등록자';
comment on column tb_popup_manage.frst_regist_pnttm is '최초 등록 일시';
comment on column tb_popup_manage.last_updusr_id is '최종 수정자';
comment on column tb_popup_manage.last_updt_pnttm is '최종 수정 일시';

---
-- tb_main_image: 메인 영역 슬라이드/히어로 이미지
---
create table if not exists tb_main_image (
    image_id varchar(20) primary key,
    domain_id varchar(20) default 'kr',
    image_nm varchar(200),
    image varchar(500),
    image_file varchar(500),
    image_dc varchar(1000),
    reflct_at char(1) default 'Y',
    frst_register_id varchar(50),
    frst_regist_pnttm timestamp default current_timestamp,
    last_updusr_id varchar(50),
    last_updt_pnttm timestamp,
    constraint fk_tb_main_image_domain foreign key (domain_id) references tb_domain_list (domain_id)
);

comment on table tb_main_image is '메인 이미지 관리';
comment on column tb_main_image.image_id is '이미지 PK (애플리케이션에서 IMG_ 접두 등)';
comment on column tb_main_image.domain_id is 'tb_domain_list 참조';
comment on column tb_main_image.image_nm is '이미지 제목';
comment on column tb_main_image.image is '이미지 경로나 URL. 기존 운영 스키마와 맞추기 위해 컬럼 이름을 image 로 둔다';
comment on column tb_main_image.image_file is '파일명';
comment on column tb_main_image.image_dc is '설명';
comment on column tb_main_image.reflct_at is '게시(반영) 여부 Y/N';
comment on column tb_main_image.frst_register_id is '최초 등록자';
comment on column tb_main_image.frst_regist_pnttm is '최초 등록 일시';
comment on column tb_main_image.last_updusr_id is '최종 수정자';
comment on column tb_main_image.last_updt_pnttm is '최종 수정 일시';

---
-- 시드
---
insert into tb_domain_list (domain_id, domain_nm, domain_path, domain_dc, use_at, sort_seq)
select 'kr', '한국어', '/kr', '한국어 메인사이트', 'Y', 1
where not exists (select 1 from tb_domain_list where domain_id = 'kr');

insert into tb_domain_list (domain_id, domain_nm, domain_path, domain_dc, use_at, sort_seq)
select 'en', 'English', '/en', 'English site', 'Y', 2
where not exists (select 1 from tb_domain_list where domain_id = 'en');

insert into tb_domain_list (domain_id, domain_nm, domain_path, domain_dc, use_at, sort_seq)
select 'tour', '관광', '/tour', '관광 사이트', 'Y', 3
where not exists (select 1 from tb_domain_list where domain_id = 'tour');

insert into tb_banner (banner_id, domain_id, banner_nm, link_url, banner_dc, sort_ordr, reflct_at, frst_register_id)
select 'BNR_001', 'kr', '샘플 배너 1', 'https://example.com', '샘플 배너입니다', 1, 'Y', 'admin'
where not exists (select 1 from tb_banner where banner_id = 'BNR_001');

insert into tb_banner (banner_id, domain_id, banner_nm, link_url, banner_dc, sort_ordr, reflct_at, frst_register_id)
select 'BNR_002', 'kr', '샘플 배너 2', 'https://example.com/2', '두번째 배너', 2, 'Y', 'admin'
where not exists (select 1 from tb_banner where banner_id = 'BNR_002');

insert into tb_banner (banner_id, domain_id, banner_nm, link_url, banner_dc, sort_ordr, reflct_at, frst_register_id)
select 'BNR_003', 'en', 'English Banner', 'https://example.com/en', 'English site banner', 1, 'Y', 'admin'
where not exists (select 1 from tb_banner where banner_id = 'BNR_003');

insert into tb_popup_manage (popup_id, domain_id, popup_sj_nm, file_url, link_target, ntce_bgnde, ntce_endde, ntce_at, stopvew_setup_at, frst_register_id)
select 'POP_001', 'kr', '안내 팝업', 'https://example.com/popup', '_blank', '202603010000', '202612312359', 'Y', 'Y', 'admin'
where not exists (select 1 from tb_popup_manage where popup_id = 'POP_001');

insert into tb_popup_manage (popup_id, domain_id, popup_sj_nm, file_url, link_target, ntce_bgnde, ntce_endde, ntce_at, stopvew_setup_at, frst_register_id)
select 'POP_002', 'kr', '이벤트 팝업', 'https://example.com/event-popup', '_self', '202606010000', '202608312359', 'Y', 'N', 'admin'
where not exists (select 1 from tb_popup_manage where popup_id = 'POP_002');

insert into tb_main_image (image_id, domain_id, image_nm, image_dc, reflct_at, frst_register_id)
select 'IMG_001', 'kr', '메인 이미지 1', '메인 슬라이드 이미지', 'Y', 'admin'
where not exists (select 1 from tb_main_image where image_id = 'IMG_001');

insert into tb_main_image (image_id, domain_id, image_nm, image_dc, reflct_at, frst_register_id)
select 'IMG_002', 'kr', '메인 이미지 2', '서브 슬라이드 이미지', 'Y', 'admin'
where not exists (select 1 from tb_main_image where image_id = 'IMG_002');

-- 마크다운 에디터 게시판 테이블 editor_documents 와 editor_assets
-- PostgreSQL용 설계와 같게 두되, 개발용 내장 DB에서는 전문 검색 인덱스 생성 구문은 생략한다
-- embedding 은 TEXT 로 저장한다

create table if not exists editor_documents (
    id uuid primary key,
    title varchar(120) not null,
    author varchar(60) not null,
    markdown clob not null,
    tags_json varchar(8000) not null default '[]',
    updated_at timestamp with time zone not null,
    embedding varchar(512) not null,
    publication_status varchar(20) not null default 'PUBLISHED',
    url_slug varchar(180),
    introduction varchar(150),
    thumbnail_image_url clob
);

create index if not exists editor_documents_updated_at_idx
    on editor_documents (updated_at desc);

create index if not exists editor_documents_publication_status_idx
    on editor_documents (publication_status, updated_at desc);

create index if not exists editor_documents_url_slug_idx
    on editor_documents (url_slug);

create table if not exists editor_assets (
    id uuid primary key,
    object_key varchar(255) not null,
    bucket_name varchar(80) not null,
    original_file_name varchar(255) not null,
    content_type varchar(160) not null,
    file_size bigint not null,
    uploaded_at timestamp with time zone not null,
    constraint uk_editor_assets_object_key unique (object_key)
);

create index if not exists editor_assets_uploaded_at_idx
    on editor_assets (uploaded_at desc);

-- 플랫폼 인증용 users 확장·비밀번호 이력·역할

ALTER TABLE users DROP CONSTRAINT chk_users_role;
ALTER TABLE users ADD CONSTRAINT chk_users_role CHECK (role IN ('USER', 'ADMIN'));

COMMENT ON COLUMN users.role IS '권한 역할(USER: 일반, ADMIN: 관리자)';

ALTER TABLE users ADD COLUMN IF NOT EXISTS account_status VARCHAR(20) NOT NULL DEFAULT 'APPROVED';
ALTER TABLE users ADD COLUMN IF NOT EXISTS platform_username VARCHAR(50) NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS login_fail_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS account_locked_at TIMESTAMP NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS password_changed_at TIMESTAMP NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS last_password_change_date DATE NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS password_change_daily_count INTEGER NOT NULL DEFAULT 0;

CREATE UNIQUE INDEX IF NOT EXISTS uq_users_platform_username ON users (platform_username);

COMMENT ON COLUMN users.account_status IS '계정 승인·정지 상태(PENDING, APPROVED, REJECTED, SUSPENDED, WITHDRAWN)';
COMMENT ON COLUMN users.platform_username IS '플랫폼 가입 시 로그인명(계정 복구 시 이메일과 함께 사용)';
COMMENT ON COLUMN users.login_fail_count IS '연속 로그인 실패 횟수';
COMMENT ON COLUMN users.account_locked_at IS '계정 잠금 처리 시각';
COMMENT ON COLUMN users.password_changed_at IS '마지막 비밀번호 변경 시각';
COMMENT ON COLUMN users.last_password_change_date IS '당일 비밀번호 변경 횟수 집계 기준일';
COMMENT ON COLUMN users.password_change_daily_count IS '기준일 당일 비밀번호 변경 횟수';

CREATE TABLE IF NOT EXISTS user_password_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    password_hash VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_user_password_history_user_created
    ON user_password_history (user_id, created_at DESC);

COMMENT ON TABLE user_password_history IS '과거 비밀번호 해시(재사용 방지 조회용)';
COMMENT ON COLUMN user_password_history.id IS '이력 행 PK';
COMMENT ON COLUMN user_password_history.user_id IS 'users.id FK';
COMMENT ON COLUMN user_password_history.password_hash IS 'BCrypt 등으로 인코딩된 비밀번호';
COMMENT ON COLUMN user_password_history.created_at IS '이력 저장 시각';

-- 역할 MANAGER 제거(USER, ADMIN만). 기존 MANAGER 행은 ADMIN으로 승격.

UPDATE users SET role = 'ADMIN' WHERE role = 'MANAGER';

ALTER TABLE users DROP CONSTRAINT chk_users_role;
ALTER TABLE users ADD CONSTRAINT chk_users_role CHECK (role IN ('USER', 'ADMIN'));

COMMENT ON COLUMN users.role IS '권한 역할(USER: 일반, ADMIN: 관리자)';

-- 구독 콘텐츠 자동 발송 스케줄
-- 콘텐츠 유형(뉴스레터·웹진 등)별로 발송 주기·요일·시각을 정의한다.
-- content_type 당 스케줄은 한 행만 허용(UK). 스케줄 비활성 시 active=false.
-- 애플리케이션의 배치/스케줄러가 이 테이블을 읽어 발송 시점을 결정한다.

create table if not exists subscription_dispatch_schedules (
    id bigint generated by default as identity primary key,
    content_type varchar(40) not null, -- 콘텐츠 유형 코드. 유형당 스케줄은 한 행만 둔다
    frequency_type varchar(20) not null, -- 반복 주기 유형. DAILY, WEEKLY 등
    day_of_week varchar(20), -- 주간 등 주기에 따른 요일. 해당 없으면 NULL
    dispatch_hour integer not null, -- 발송 시각(시, 0–23)
    dispatch_minute integer not null, -- 발송 시각(분, 0–59)
    active boolean not null default true, -- 스케줄 사용 여부
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,
    constraint uk_subscription_dispatch_schedule_content_type unique (content_type)
);

create index if not exists idx_subscription_dispatch_schedules_active
    on subscription_dispatch_schedules(active);

comment on table subscription_dispatch_schedules is '구독 콘텐츠 자동 발송 스케줄(유형별 주기·시각)';
comment on column subscription_dispatch_schedules.id is '스케줄 행 PK';
comment on column subscription_dispatch_schedules.content_type is '콘텐츠 유형 코드. 유형당 스케줄 행은 하나만 둔다.';
comment on column subscription_dispatch_schedules.frequency_type is '반복 주기 유형. DAILY, WEEKLY, MONTHLY 등.';
comment on column subscription_dispatch_schedules.day_of_week is '주간 등 주기에 따른 요일(애플리케이션 규약 문자열). 해당 없으면 NULL';
comment on column subscription_dispatch_schedules.dispatch_hour is '발송 시각(시, 0–23)';
comment on column subscription_dispatch_schedules.dispatch_minute is '발송 시각(분, 0–59)';
comment on column subscription_dispatch_schedules.active is '스케줄 사용 여부(배치에서 false 행은 건너뜀)';
comment on column subscription_dispatch_schedules.created_at is '행 생성 시각';
comment on column subscription_dispatch_schedules.updated_at is '마지막 수정 시각';

-- 인증·검증 시도 감사 로그
-- 가입이나 비밀번호 찾기처럼 이메일·계정 검증을 시도할 때마다 한 행으로 남긴다.
-- 서버가 기록하고, 운영 화면에서 유형·키워드로 찾는다.
-- 인덱스는 최근 로그와 유형별 최근 로그 조회에 맞춘다.

create table if not exists auth_verification_audit_logs (
    id                 bigint        not null generated by default as identity primary key,
    verification_type  varchar(64)   not null, -- 검증 유형(애플리케이션 규약 문자열, 예: SIGNUP_EMAIL)
    email              varchar(190),           -- 대상 이메일(없으면 null)
    username           varchar(120),           -- 대상 사용자명·닉네임 등(없으면 null)
    ip_address         varchar(64)   not null, -- 클라이언트 IP(최대 64자)
    success            boolean       not null, -- 검증 성공 여부
    detail             varchar(500),           -- 실패 사유·추가 맥락(없으면 null)
    created_at         timestamp(6)  not null  -- 기록 시각
);

create index if not exists idx_auth_verification_audit_logs_created_at
    on auth_verification_audit_logs (created_at desc);

create index if not exists idx_auth_verification_audit_logs_type_created
    on auth_verification_audit_logs (verification_type, created_at desc);

comment on table auth_verification_audit_logs is '인증·검증(이메일 코드 등) 시도 감사 로그';
comment on column auth_verification_audit_logs.id is '로그 PK 자동 증가';
comment on column auth_verification_audit_logs.verification_type is '검증 유형 코드(서비스에서 정의한 문자열)';
comment on column auth_verification_audit_logs.email is '시도에 사용된 이메일 주소';
comment on column auth_verification_audit_logs.username is '시도에 사용된 사용자명 또는 닉네임';
comment on column auth_verification_audit_logs.ip_address is '요청 클라이언트 IP 주소';
comment on column auth_verification_audit_logs.success is '검증 성공 여부(true 성공, false 실패)';
comment on column auth_verification_audit_logs.detail is '실패 사유·메모 등 부가 설명(최대 500자)';
comment on column auth_verification_audit_logs.created_at is '로그가 기록된 시각';

-- 계정 검증용 일회성 토큰
-- 이메일 가입 인증이나 계정 확인에 쓰는 토큰을 저장한다.
-- 인덱스는 토큰 단건 조회와 이메일·유형·상태별 최신 행 조회에 맞춘다.

create table if not exists signup_verification_tokens (
    id             bigint        not null generated by default as identity primary key,
    token          varchar(120)  not null, -- 일회성 검증 토큰(전역 유일)
    type           varchar(40)   not null, -- 검증 유형 코드
    email          varchar(190)  not null, -- 대상 이메일
    username       varchar(120),           -- 닉네임 등(선택)
    user_id        bigint,                 -- 확인 후 연결된 users.id(선택)
    status         varchar(30)   not null, -- 토큰 상태 코드
    requested_ip   varchar(64)   not null, -- 발급 요청 IP
    confirmed_ip   varchar(64),            -- 검증 완료 시 IP(선택)
    expires_at     timestamp(6)  not null, -- 만료 시각
    created_at     timestamp(6)  not null, -- 행 생성 시각
    confirmed_at   timestamp(6),           -- 검증·사용 완료 시각(선택)
    detail         varchar(500),           -- 거절 사유 등(선택)
    constraint uk_signup_verification_tokens_token unique (token)
);

create index if not exists idx_signup_verification_tokens_email_type_status_created
    on signup_verification_tokens (email, type, status, created_at desc);

comment on table signup_verification_tokens is '가입·계정 확인용 검증 토큰 저장소';
comment on column signup_verification_tokens.id is '행 PK';
comment on column signup_verification_tokens.token is '클라이언트에 전달하는 불투명 토큰(유일)';
comment on column signup_verification_tokens.type is '검증 유형 코드. EMAIL_SIGNUP_VERIFY, ACCOUNT_CONFIRM 등 서비스에서 정의';
comment on column signup_verification_tokens.email is '검증 대상 이메일';
comment on column signup_verification_tokens.username is '표시용 사용자명·닉네임(있을 때만)';
comment on column signup_verification_tokens.user_id is '검증 완료 후 매핑된 사용자 PK';
comment on column signup_verification_tokens.status is 'PENDING, VERIFIED, USED, REJECTED, EXPIRED';
comment on column signup_verification_tokens.requested_ip is '토큰 발급 요청 IP';
comment on column signup_verification_tokens.confirmed_ip is '토큰 검증 요청 IP';
comment on column signup_verification_tokens.expires_at is '토큰 만료 시각';
comment on column signup_verification_tokens.created_at is '레코드 생성 시각';
comment on column signup_verification_tokens.confirmed_at is '검증 또는 사용 처리 시각';
comment on column signup_verification_tokens.detail is '실패·거절 시 부가 설명';

-- idx_signup_verification_tokens_email_type_status_created → 이메일·유형·상태별 최신 토큰 조회

-- users: 임시 비밀번호를 마지막으로 발급한 시각
-- 재발급 간격이나 만료 정책에 쓴다. 값이 없으면 아직 발급 이력이 없다.

alter table users
    add column if not exists temporary_password_issued_at timestamp(6);

comment on column users.temporary_password_issued_at is '플랫폼 임시 비밀번호를 마지막으로 발급한 시각. 미발급이면 NULL';

-- users: 다음 로그인 때 비밀번호를 바꾸게 할지 여부
-- 임시 비밀번호를 준 뒤 등 보안 정책에 쓴다. 기본값은 false 이다.

alter table users
    add column if not exists temporary_password_required boolean not null default false;

comment on column users.temporary_password_required is '임시 비밀번호 발급 등으로 인해 비밀번호 변경이 필요하면 true';
