-- =============================================================================
-- Flyway V22 - 구독 콘텐츠 자동 발송 스케줄
-- =============================================================================
-- 콘텐츠 유형(뉴스레터·웹진 등)별로 발송 주기·요일·시각을 정의한다.
-- content_type 당 스케줄은 한 행만 허용(UK). 스케줄 비활성 시 active=false.
-- 애플리케이션의 배치/스케줄러가 이 테이블을 읽어 발송 시점을 결정한다.
-- =============================================================================

create table if not exists subscription_dispatch_schedules (
    id bigint generated by default as identity primary key,
    content_type varchar(40) not null, -- 콘텐츠 유형(예: NEWSLETTER, WEBZINE). 전역 유일
    frequency_type varchar(20) not null, -- 반복 주기 유형(예: DAILY, WEEKLY)
    day_of_week varchar(20), -- 주간 등 주기에 따른 요일. 해당 없으면 NULL
    dispatch_hour integer not null, -- 발송 시각(시, 0–23)
    dispatch_minute integer not null, -- 발송 시각(분, 0–59)
    active boolean not null default true, -- 스케줄 사용 여부
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,
    constraint uk_subscription_dispatch_schedule_content_type unique (content_type)
);

create index if not exists idx_subscription_dispatch_schedules_active
    on subscription_dispatch_schedules(active);

comment on table subscription_dispatch_schedules is '구독 콘텐츠 자동 발송 스케줄(유형별 주기·시각)';
comment on column subscription_dispatch_schedules.id is '스케줄 행 PK';
comment on column subscription_dispatch_schedules.content_type is '콘텐츠 유형(예: NEWSLETTER, WEBZINE). 전역 유일';
comment on column subscription_dispatch_schedules.frequency_type is '반복 주기 유형(예: DAILY, WEEKLY, MONTHLY)';
comment on column subscription_dispatch_schedules.day_of_week is '주간 등 주기에 따른 요일(애플리케이션 규약 문자열). 해당 없으면 NULL';
comment on column subscription_dispatch_schedules.dispatch_hour is '발송 시각(시, 0–23)';
comment on column subscription_dispatch_schedules.dispatch_minute is '발송 시각(분, 0–59)';
comment on column subscription_dispatch_schedules.active is '스케줄 사용 여부(배치에서 false 행은 건너뜀)';
comment on column subscription_dispatch_schedules.created_at is '행 생성 시각';
comment on column subscription_dispatch_schedules.updated_at is '마지막 수정 시각';
