-- =============================================================================
-- Flyway V23  - 인증 검증 감사 로그
-- =============================================================================
-- 목적
--   가입·비밀번호 찾기 등 이메일/계정 검증 시도를 한 행으로 남긴다.
--   AdminAuthVerificationController·AuthVerificationAuditService 가 INSERT 하며
--   운영자는 유형·키워드로 페이지 조회한다.
-- =============================================================================
-- 인덱스
--   created_at 내림차순: 최근 로그 목록
--   verification_type + created_at: 유형별 최근 로그
-- =============================================================================

create table if not exists auth_verification_audit_logs (
    id                 bigint        not null generated by default as identity primary key,
    verification_type  varchar(64)   not null, -- 검증 유형(애플리케이션 규약 문자열, 예: SIGNUP_EMAIL)
    email              varchar(190),           -- 대상 이메일(없으면 null)
    username           varchar(120),           -- 대상 사용자명·닉네임 등(없으면 null)
    ip_address         varchar(64)   not null, -- 클라이언트 IP(최대 64자)
    success            boolean       not null, -- 검증 성공 여부
    detail             varchar(500),           -- 실패 사유·추가 맥락(없으면 null)
    created_at         timestamp(6)  not null  -- 기록 시각
);

create index if not exists idx_auth_verification_audit_logs_created_at
    on auth_verification_audit_logs (created_at desc);

create index if not exists idx_auth_verification_audit_logs_type_created
    on auth_verification_audit_logs (verification_type, created_at desc);

comment on table auth_verification_audit_logs is '인증·검증(이메일 코드 등) 시도 감사 로그';
comment on column auth_verification_audit_logs.id is '로그 PK 자동 증가';
comment on column auth_verification_audit_logs.verification_type is '검증 유형 코드(서비스에서 정의한 문자열)';
comment on column auth_verification_audit_logs.email is '시도에 사용된 이메일 주소';
comment on column auth_verification_audit_logs.username is '시도에 사용된 사용자명 또는 닉네임';
comment on column auth_verification_audit_logs.ip_address is '요청 클라이언트 IP 주소';
comment on column auth_verification_audit_logs.success is '검증 성공 여부(true 성공, false 실패)';
comment on column auth_verification_audit_logs.detail is '실패 사유·메모 등 부가 설명(최대 500자)';
comment on column auth_verification_audit_logs.created_at is '로그가 기록된 시각';

