-- =============================================================================
-- Flyway V24  - 가입·계정 검증 토큰
-- =============================================================================
-- 목적
--   이메일 가입 인증, 계정 확인 등 일회성 토큰을 저장한다.
--   SignupVerificationToken 엔티티·SignupVerificationTokenRepository 가 사용한다.
-- 인덱스
--   token UK: 토큰으로 단건 조회
--   email+type+status+created_at: 최신 유효 행 조회
-- =============================================================================

create table if not exists signup_verification_tokens (
    id             bigint        not null generated by default as identity primary key,
    token          varchar(120)  not null, -- 일회성 검증 토큰(전역 유일)
    type           varchar(40)   not null, -- SignupVerificationType 문자열
    email          varchar(190)  not null, -- 대상 이메일
    username       varchar(120),           -- 닉네임 등(선택)
    user_id        bigint,                 -- 확인 후 연결된 users.id(선택)
    status         varchar(30)   not null, -- SignupVerificationStatus 문자열
    requested_ip   varchar(64)   not null, -- 발급 요청 IP
    confirmed_ip   varchar(64),            -- 검증 완료 시 IP(선택)
    expires_at     timestamp(6)  not null, -- 만료 시각
    created_at     timestamp(6)  not null, -- 행 생성 시각
    confirmed_at   timestamp(6),           -- 검증·사용 완료 시각(선택)
    detail         varchar(500),           -- 거절 사유 등(선택)
    constraint uk_signup_verification_tokens_token unique (token)
);

create index if not exists idx_signup_verification_tokens_email_type_status_created
    on signup_verification_tokens (email, type, status, created_at desc);

comment on table signup_verification_tokens is '가입·계정 확인용 검증 토큰 저장소';
comment on column signup_verification_tokens.id is '행 PK';
comment on column signup_verification_tokens.token is '클라이언트에 전달하는 불투명 토큰(유일)';
comment on column signup_verification_tokens.type is '검증 유형(EMAIL_SIGNUP_VERIFY, ACCOUNT_CONFIRM 등)';
comment on column signup_verification_tokens.email is '검증 대상 이메일';
comment on column signup_verification_tokens.username is '표시용 사용자명·닉네임(있을 때만)';
comment on column signup_verification_tokens.user_id is '검증 완료 후 매핑된 사용자 PK';
comment on column signup_verification_tokens.status is 'PENDING, VERIFIED, USED, REJECTED, EXPIRED';
comment on column signup_verification_tokens.requested_ip is '토큰 발급 요청 IP';
comment on column signup_verification_tokens.confirmed_ip is '토큰 검증 요청 IP';
comment on column signup_verification_tokens.expires_at is '토큰 만료 시각';
comment on column signup_verification_tokens.created_at is '레코드 생성 시각';
comment on column signup_verification_tokens.confirmed_at is '검증 또는 사용 처리 시각';
comment on column signup_verification_tokens.detail is '실패·거절 시 부가 설명';

-- idx_signup_verification_tokens_email_type_status_created → 이메일·유형·상태별 최신 토큰 조회
