CREATE TABLE IF NOT EXISTS exchange_branch (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(200) NOT NULL,
    rate NUMERIC(20, 8) NOT NULL,
    currency VARCHAR(8) NOT NULL,
    lat DOUBLE PRECISION NOT NULL,
    lng DOUBLE PRECISION NOT NULL,
    sort_order INT NOT NULL DEFAULT 0,
    airport_hub BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX IF NOT EXISTS idx_exchange_branch_currency ON exchange_branch (currency);

CREATE TABLE IF NOT EXISTS exchange_alert (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users (id),
    from_currency VARCHAR(8) NOT NULL,
    to_currency VARCHAR(8) NOT NULL,
    target_rate NUMERIC(20, 8) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_exchange_alert_user ON exchange_alert (user_id);

INSERT INTO exchange_branch (name, rate, currency, lat, lng, sort_order, airport_hub)
SELECT v.name, v.rate, v.currency, v.lat, v.lng, v.sort_order, v.airport_hub
FROM (
    VALUES
        ('IdolGlow 공항 환전', 9.33, 'JPY', 37.4602, 126.4407, 0, TRUE),
        ('명동 대사관', 9.23, 'JPY', 37.5635, 126.9826, 1, FALSE),
        ('명동 제1교류센터', 9.23, 'JPY', 37.5640, 126.9815, 2, FALSE),
        ('환전 카페 (구 입핀상)', 9.23, 'JPY', 37.5632, 126.9850, 3, FALSE),
        ('명동 돈 상자', 9.2283, 'JPY', 37.5628, 126.9838, 4, FALSE)
) AS v(name, rate, currency, lat, lng, sort_order, airport_hub)
WHERE NOT EXISTS (SELECT 1 FROM exchange_branch);
