CREATE TABLE IF NOT EXISTS survey_form_description (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    survey_form_id BIGINT NOT NULL,
    markdown TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_survey_form_description_form
        FOREIGN KEY (survey_form_id)
        REFERENCES survey_form (id)
        ON DELETE CASCADE,
    CONSTRAINT uk_survey_form_description_form UNIQUE (survey_form_id)
);

CREATE TABLE IF NOT EXISTS survey_form_description_tag (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    survey_form_description_id BIGINT NOT NULL,
    display_order INT NOT NULL,
    tag_name VARCHAR(100) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_survey_form_description_tag_description
        FOREIGN KEY (survey_form_description_id)
        REFERENCES survey_form_description (id)
        ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_survey_form_description_tag_description_id
    ON survey_form_description_tag (survey_form_description_id);

INSERT INTO survey_form_description (survey_form_id, markdown, created_at, updated_at)
SELECT f.id, f.description, COALESCE(f.created_at, CURRENT_TIMESTAMP), COALESCE(f.updated_at, CURRENT_TIMESTAMP)
FROM survey_form f
WHERE f.description IS NOT NULL
  AND TRIM(f.description) <> ''
  AND NOT EXISTS (
      SELECT 1
      FROM survey_form_description d
      WHERE d.survey_form_id = f.id
  );

COMMENT ON TABLE survey_form_description IS '설문 설명 마크다운 본문';
COMMENT ON COLUMN survey_form_description.survey_form_id IS '소속 설문지 ID(FK)';
COMMENT ON COLUMN survey_form_description.markdown IS '설문 설명 마크다운';

COMMENT ON TABLE survey_form_description_tag IS '설문 설명 태그 목록';
COMMENT ON COLUMN survey_form_description_tag.survey_form_description_id IS '소속 설문 설명 ID(FK)';
COMMENT ON COLUMN survey_form_description_tag.display_order IS '태그 노출 순서';
COMMENT ON COLUMN survey_form_description_tag.tag_name IS '태그명';
