-- =============================================================================
-- V5: images 테이블 보장
-- flyway_schema_history는 최신인데 테이블만 누락된 DB(덤프 복원, 수동 DDL 등)를 복구한다.
-- V3과 동일 구조이며 INSERT는 넣지 않는다(운영 데이터 오염 방지).
-- =============================================================================

CREATE TABLE IF NOT EXISTS images (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aggregate_type VARCHAR(30) NOT NULL,
    aggregate_id BIGINT NOT NULL,
    original_filename VARCHAR(255) NOT NULL,
    unique_filename VARCHAR(255) NOT NULL,
    extension VARCHAR(20) NOT NULL,
    file_size BIGINT NOT NULL,
    url VARCHAR(500) NOT NULL,
    sort_order INT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT chk_images_aggregate_type CHECK (aggregate_type IN ('PRODUCT', 'OPTION', 'USER', 'PRODUCT_REVIEW')),
    CONSTRAINT chk_images_sort_order CHECK (sort_order >= 0),
    CONSTRAINT chk_images_file_size CHECK (file_size > 0)
);

CREATE INDEX IF NOT EXISTS idx_images_aggregate ON images (aggregate_type, aggregate_id, sort_order);

COMMENT ON TABLE images IS '도메인 엔티티별 저장 이미지 메타';
COMMENT ON COLUMN images.id IS '이미지 PK(자동 증가)';
COMMENT ON COLUMN images.aggregate_type IS '이미지가 속한 도메인 타입(PRODUCT/OPTION/USER/PRODUCT_REVIEW)';
COMMENT ON COLUMN images.aggregate_id IS 'aggregate_type에 해당하는 실제 엔티티 PK';
COMMENT ON COLUMN images.original_filename IS '사용자가 업로드한 원본 파일명';
COMMENT ON COLUMN images.unique_filename IS '스토리지 저장용 유니크 파일명';
COMMENT ON COLUMN images.extension IS '파일 확장자(예: jpg, png)';
COMMENT ON COLUMN images.file_size IS '파일 크기(byte)';
COMMENT ON COLUMN images.url IS '클라이언트가 접근 가능한 이미지 URL';
COMMENT ON COLUMN images.sort_order IS '동일 엔티티 내 이미지 정렬 순서(0부터)';
COMMENT ON COLUMN images.created_at IS '생성 시각';
COMMENT ON COLUMN images.updated_at IS '수정 시각';
