/**
 * ISO 4217(3자) → 국기 이미지용 ISO 3166-1 alpha-2 (소문자, flagcdn.com).
 * 복수 국가 통화(EUR 등)는 관례적으로 쓰이는 코드를 사용합니다.
 */
const CURRENCY_TO_CC: Record<string, string> = {
  AED: 'ae',
  AFN: 'af',
  ALL: 'al',
  AMD: 'am',
  ARS: 'ar',
  AUD: 'au',
  AZN: 'az',
  BAM: 'ba',
  BDT: 'bd',
  BGN: 'bg',
  BHD: 'bh',
  BND: 'bn',
  BOB: 'bo',
  BRL: 'br',
  BWP: 'bw',
  BYN: 'by',
  CAD: 'ca',
  CHF: 'ch',
  CLP: 'cl',
  CNY: 'cn',
  COP: 'co',
  CRC: 'cr',
  CZK: 'cz',
  DKK: 'dk',
  DOP: 'do',
  DZD: 'dz',
  EGP: 'eg',
  ETB: 'et',
  EUR: 'eu',
  FJD: 'fj',
  GBP: 'gb',
  GEL: 'ge',
  GHS: 'gh',
  GNF: 'gn',
  GTQ: 'gt',
  HKD: 'hk',
  HNL: 'hn',
  HRK: 'hr',
  HUF: 'hu',
  IDR: 'id',
  ILS: 'il',
  INR: 'in',
  IQD: 'iq',
  IRR: 'ir',
  ISK: 'is',
  JOD: 'jo',
  JPY: 'jp',
  KES: 'ke',
  KGS: 'kg',
  KHR: 'kh',
  KRW: 'kr',
  KWD: 'kw',
  KZT: 'kz',
  LAK: 'la',
  LBP: 'lb',
  LKR: 'lk',
  MAD: 'ma',
  MDL: 'md',
  MNT: 'mn',
  MVR: 'mv',
  MXN: 'mx',
  MYR: 'my',
  NGN: 'ng',
  NIO: 'ni',
  NOK: 'no',
  NPR: 'np',
  NZD: 'nz',
  OMR: 'om',
  PAB: 'pa',
  PEN: 'pe',
  PHP: 'ph',
  PKR: 'pk',
  PLN: 'pl',
  PYG: 'py',
  QAR: 'qa',
  RON: 'ro',
  RSD: 'rs',
  RUB: 'ru',
  RWF: 'rw',
  SAR: 'sa',
  SEK: 'se',
  SGD: 'sg',
  SYP: 'sy',
  THB: 'th',
  TJS: 'tj',
  TMT: 'tm',
  TND: 'tn',
  TRY: 'tr',
  TWD: 'tw',
  TZS: 'tz',
  UAH: 'ua',
  UGX: 'ug',
  USD: 'us',
  UYU: 'uy',
  UZS: 'uz',
  VND: 'vn',
  XAF: 'cm',
  XOF: 'sn',
  ZAR: 'za',
  ZMW: 'zm',
};

export function currencyToFlagCountry(iso4217Base: string): string | null {
  const c = iso4217Base.trim().toUpperCase();
  if (!/^[A-Z]{3}$/.test(c)) return null;
  return CURRENCY_TO_CC[c] ?? null;
}
